// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/proxy/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Cache
func (_mock *Cache) Close() {
	_mock.Called()
	return
}

// Cache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Cache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Cache_Expecter) Close() *Cache_Close_Call {
	return &Cache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Cache_Close_Call) Run(run func()) *Cache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cache_Close_Call) Return() *Cache_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Cache_Close_Call) RunAndReturn(run func()) *Cache_Close_Call {
	_c.Run(run)
	return _c
}

// GetBlocklistEntry provides a mock function for the type Cache
func (_mock *Cache) GetBlocklistEntry(ctx context.Context, blocklistId string, domain string) (bool, error) {
	ret := _mock.Called(ctx, blocklistId, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocklistEntry")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, blocklistId, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, blocklistId, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, blocklistId, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetBlocklistEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocklistEntry'
type Cache_GetBlocklistEntry_Call struct {
	*mock.Call
}

// GetBlocklistEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - blocklistId string
//   - domain string
func (_e *Cache_Expecter) GetBlocklistEntry(ctx interface{}, blocklistId interface{}, domain interface{}) *Cache_GetBlocklistEntry_Call {
	return &Cache_GetBlocklistEntry_Call{Call: _e.mock.On("GetBlocklistEntry", ctx, blocklistId, domain)}
}

func (_c *Cache_GetBlocklistEntry_Call) Run(run func(ctx context.Context, blocklistId string, domain string)) *Cache_GetBlocklistEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cache_GetBlocklistEntry_Call) Return(b bool, err error) *Cache_GetBlocklistEntry_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Cache_GetBlocklistEntry_Call) RunAndReturn(run func(ctx context.Context, blocklistId string, domain string) (bool, error)) *Cache_GetBlocklistEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileSettingsBatch provides a mock function for the type Cache
func (_mock *Cache) GetProfileSettingsBatch(ctx context.Context, profileId string) (*model.ProfileSettings, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileSettingsBatch")
	}

	var r0 *model.ProfileSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ProfileSettings, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ProfileSettings); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProfileSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileSettingsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileSettingsBatch'
type Cache_GetProfileSettingsBatch_Call struct {
	*mock.Call
}

// GetProfileSettingsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileSettingsBatch(ctx interface{}, profileId interface{}) *Cache_GetProfileSettingsBatch_Call {
	return &Cache_GetProfileSettingsBatch_Call{Call: _e.mock.On("GetProfileSettingsBatch", ctx, profileId)}
}

func (_c *Cache_GetProfileSettingsBatch_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileSettingsBatch_Call) Return(profileSettings *model.ProfileSettings, err error) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Return(profileSettings, err)
	return _c
}

func (_c *Cache_GetProfileSettingsBatch_Call) RunAndReturn(run func(ctx context.Context, profileId string) (*model.ProfileSettings, error)) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Return(run)
	return _c
}
