services:
  dnscheck:
    build:
      context: .
      dockerfile: dnscheck/Dockerfile
    image: dnscheck:latest
    restart: always
    command: sleep infinity
    networks:
      - dnsnetwork
    container_name: dnscheck
    ports:
      - "80:3000"
      - "30000:53/udp"
      - "30000:53/tcp"
    volumes:
      - ./dnscheck:/app
      - ./dev/bootstrap/GeoLite2-ASN/:/opt/dnscheck/GeoIP
      - ./dev/bootstrap/GeoLite2-City/:/opt/dnscheck/GeoIPCity
      # - ./dev/certs:/certs
    env_file:
      - ./dnscheck/.env
