# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.requests_rotate_pa_session_req import RequestsRotatePASessionReq

class TestRequestsRotatePASessionReq(unittest.TestCase):
    """RequestsRotatePASessionReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestsRotatePASessionReq:
        """Test RequestsRotatePASessionReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestsRotatePASessionReq`
        """
        model = RequestsRotatePASessionReq()
        if include_optional:
            return RequestsRotatePASessionReq(
                sessionid = ''
            )
        else:
            return RequestsRotatePASessionReq(
                sessionid = '',
        )
        """

    def testRequestsRotatePASessionReq(self):
        """Test RequestsRotatePASessionReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
