# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.pa_session_api import PASessionApi


class TestPASessionApi(unittest.TestCase):
    """PASessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PASessionApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_pasession_add_post(self) -> None:
        """Test case for api_v1_pasession_add_post

        Add pre-auth session
        """
        pass

    def test_api_v1_pasession_rotate_put(self) -> None:
        """Test case for api_v1_pasession_rotate_put

        Rotate pre-auth session ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
