# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from moddns.models.model_statistics_device import ModelStatisticsDevice
from moddns.models.model_statistics_point import ModelStatisticsPoint
from moddns.models.model_statistics_protocols import ModelStatisticsProtocols
from moddns.models.model_statistics_reasons import ModelStatisticsReasons
from moddns.models.model_statistics_totals import ModelStatisticsTotals
from typing import Optional, Set
from typing_extensions import Self

class ModelStatisticsResponse(BaseModel):
    """
    ModelStatisticsResponse
    """ # noqa: E501
    bucket_seconds: Optional[StrictInt] = None
    devices: Optional[List[ModelStatisticsDevice]] = None
    enabled: Optional[StrictBool] = None
    enabled_at: Optional[StrictStr] = None
    var_from: Optional[StrictStr] = Field(default=None, alias="from")
    history_deleted_at: Optional[StrictStr] = Field(default=None, description="Last \"Delete statistics history\" (J53); null while off or never deleted.")
    protocols: Optional[ModelStatisticsProtocols] = None
    reasons: Optional[ModelStatisticsReasons] = None
    retention: Optional[StrictStr] = None
    series: Optional[List[ModelStatisticsPoint]] = None
    timespan: Optional[StrictStr] = None
    to: Optional[StrictStr] = None
    totals: Optional[ModelStatisticsTotals] = None
    __properties: ClassVar[List[str]] = ["bucket_seconds", "devices", "enabled", "enabled_at", "from", "history_deleted_at", "protocols", "reasons", "retention", "series", "timespan", "to", "totals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelStatisticsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in devices (list)
        _items = []
        if self.devices:
            for _item_devices in self.devices:
                if _item_devices:
                    _items.append(_item_devices.to_dict())
            _dict['devices'] = _items
        # override the default output from pydantic by calling `to_dict()` of protocols
        if self.protocols:
            _dict['protocols'] = self.protocols.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reasons
        if self.reasons:
            _dict['reasons'] = self.reasons.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in series (list)
        _items = []
        if self.series:
            for _item_series in self.series:
                if _item_series:
                    _items.append(_item_series.to_dict())
            _dict['series'] = _items
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelStatisticsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucket_seconds": obj.get("bucket_seconds"),
            "devices": [ModelStatisticsDevice.from_dict(_item) for _item in obj["devices"]] if obj.get("devices") is not None else None,
            "enabled": obj.get("enabled"),
            "enabled_at": obj.get("enabled_at"),
            "from": obj.get("from"),
            "history_deleted_at": obj.get("history_deleted_at"),
            "protocols": ModelStatisticsProtocols.from_dict(obj["protocols"]) if obj.get("protocols") is not None else None,
            "reasons": ModelStatisticsReasons.from_dict(obj["reasons"]) if obj.get("reasons") is not None else None,
            "retention": obj.get("retention"),
            "series": [ModelStatisticsPoint.from_dict(_item) for _item in obj["series"]] if obj.get("series") is not None else None,
            "timespan": obj.get("timespan"),
            "to": obj.get("to"),
            "totals": ModelStatisticsTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None
        })
        return _obj


