# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from moddns.models.model_statistics_retention import ModelStatisticsRetention
from typing import Optional, Set
from typing_extensions import Self

class ModelStatisticsSettings(BaseModel):
    """
    ModelStatisticsSettings
    """ # noqa: E501
    enabled: StrictBool
    enabled_at: Optional[StrictStr] = Field(default=None, description="When statistics were last turned on (UTC). Absent while statistics are off.")
    history_deleted_at: Optional[StrictStr] = Field(default=None, description="Last \"Delete statistics history\" while on (UTC); bounds what is kept (J53). Not in Redis, not exported (F21).")
    retention: Optional[ModelStatisticsRetention] = Field(default=None, description="No omitempty: HSET merges fields, so an omitted value would leave a stale one (J48).")
    __properties: ClassVar[List[str]] = ["enabled", "enabled_at", "history_deleted_at", "retention"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelStatisticsSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelStatisticsSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "enabled_at": obj.get("enabled_at"),
            "history_deleted_at": obj.get("history_deleted_at"),
            "retention": obj.get("retention")
        })
        return _obj


