# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moddns.models.model_custom_rule_group import ModelCustomRuleGroup
from typing import Optional, Set
from typing_extensions import Self

class ModelCustomRuleGroups(BaseModel):
    """
    ModelCustomRuleGroups
    """ # noqa: E501
    allow: Optional[Annotated[List[ModelCustomRuleGroup], Field(max_length=100)]] = None
    block: Optional[Annotated[List[ModelCustomRuleGroup], Field(max_length=100)]] = None
    __properties: ClassVar[List[str]] = ["allow", "block"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelCustomRuleGroups from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in allow (list)
        _items = []
        if self.allow:
            for _item_allow in self.allow:
                if _item_allow:
                    _items.append(_item_allow.to_dict())
            _dict['allow'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in block (list)
        _items = []
        if self.block:
            for _item_block in self.block:
                if _item_block:
                    _items.append(_item_block.to_dict())
            _dict['block'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelCustomRuleGroups from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow": [ModelCustomRuleGroup.from_dict(_item) for _item in obj["allow"]] if obj.get("allow") is not None else None,
            "block": [ModelCustomRuleGroup.from_dict(_item) for _item in obj["block"]] if obj.get("block") is not None else None
        })
        return _obj


