# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moddns.models.requests_exported_from_info import RequestsExportedFromInfo
from moddns.models.requests_import_profile import RequestsImportProfile
from typing import Optional, Set
from typing_extensions import Self

class RequestsImportPayload(BaseModel):
    """
    RequestsImportPayload
    """ # noqa: E501
    exported_at: StrictStr = Field(alias="exportedAt")
    exported_from: Optional[RequestsExportedFromInfo] = Field(default=None, alias="exportedFrom")
    kind: StrictStr
    profiles: Annotated[List[RequestsImportProfile], Field(min_length=1, max_length=10)]
    schema_version: StrictInt = Field(alias="schemaVersion")
    __properties: ClassVar[List[str]] = ["exportedAt", "exportedFrom", "kind", "profiles", "schemaVersion"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestsImportPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of exported_from
        if self.exported_from:
            _dict['exportedFrom'] = self.exported_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in profiles (list)
        _items = []
        if self.profiles:
            for _item_profiles in self.profiles:
                if _item_profiles:
                    _items.append(_item_profiles.to_dict())
            _dict['profiles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestsImportPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exportedAt": obj.get("exportedAt"),
            "exportedFrom": RequestsExportedFromInfo.from_dict(obj["exportedFrom"]) if obj.get("exportedFrom") is not None else None,
            "kind": obj.get("kind"),
            "profiles": [RequestsImportProfile.from_dict(_item) for _item in obj["profiles"]] if obj.get("profiles") is not None else None,
            "schemaVersion": obj.get("schemaVersion")
        })
        return _obj


