# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moddns.models.requests_import_advanced import RequestsImportAdvanced
from moddns.models.requests_import_custom_rule import RequestsImportCustomRule
from moddns.models.requests_import_logs import RequestsImportLogs
from moddns.models.requests_import_privacy import RequestsImportPrivacy
from moddns.models.requests_import_security import RequestsImportSecurity
from moddns.models.requests_import_statistics import RequestsImportStatistics
from typing import Optional, Set
from typing_extensions import Self

class RequestsImportSettings(BaseModel):
    """
    RequestsImportSettings
    """ # noqa: E501
    advanced: Optional[RequestsImportAdvanced] = None
    custom_rules: Optional[Annotated[List[RequestsImportCustomRule], Field(max_length=10000)]] = Field(default=None, alias="customRules")
    logs: Optional[RequestsImportLogs] = None
    privacy: Optional[RequestsImportPrivacy] = None
    security: Optional[RequestsImportSecurity] = None
    statistics: Optional[RequestsImportStatistics] = None
    __properties: ClassVar[List[str]] = ["advanced", "customRules", "logs", "privacy", "security", "statistics"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestsImportSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of advanced
        if self.advanced:
            _dict['advanced'] = self.advanced.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in custom_rules (list)
        _items = []
        if self.custom_rules:
            for _item_custom_rules in self.custom_rules:
                if _item_custom_rules:
                    _items.append(_item_custom_rules.to_dict())
            _dict['customRules'] = _items
        # override the default output from pydantic by calling `to_dict()` of logs
        if self.logs:
            _dict['logs'] = self.logs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of privacy
        if self.privacy:
            _dict['privacy'] = self.privacy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of security
        if self.security:
            _dict['security'] = self.security.to_dict()
        # override the default output from pydantic by calling `to_dict()` of statistics
        if self.statistics:
            _dict['statistics'] = self.statistics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestsImportSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "advanced": RequestsImportAdvanced.from_dict(obj["advanced"]) if obj.get("advanced") is not None else None,
            "customRules": [RequestsImportCustomRule.from_dict(_item) for _item in obj["customRules"]] if obj.get("customRules") is not None else None,
            "logs": RequestsImportLogs.from_dict(obj["logs"]) if obj.get("logs") is not None else None,
            "privacy": RequestsImportPrivacy.from_dict(obj["privacy"]) if obj.get("privacy") is not None else None,
            "security": RequestsImportSecurity.from_dict(obj["security"]) if obj.get("security") is not None else None,
            "statistics": RequestsImportStatistics.from_dict(obj["statistics"]) if obj.get("statistics") is not None else None
        })
        return _obj


