// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAccountPurgercron creates a new instance of AccountPurgercron. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountPurgercron(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountPurgercron {
	mock := &AccountPurgercron{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountPurgercron is an autogenerated mock type for the AccountPurger type
type AccountPurgercron struct {
	mock.Mock
}

type AccountPurgercron_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountPurgercron) EXPECT() *AccountPurgercron_Expecter {
	return &AccountPurgercron_Expecter{mock: &_m.Mock}
}

// PurgeAccountData provides a mock function for the type AccountPurgercron
func (_mock *AccountPurgercron) PurgeAccountData(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for PurgeAccountData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountPurgercron_PurgeAccountData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeAccountData'
type AccountPurgercron_PurgeAccountData_Call struct {
	*mock.Call
}

// PurgeAccountData is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *AccountPurgercron_Expecter) PurgeAccountData(ctx interface{}, accountId interface{}) *AccountPurgercron_PurgeAccountData_Call {
	return &AccountPurgercron_PurgeAccountData_Call{Call: _e.mock.On("PurgeAccountData", ctx, accountId)}
}

func (_c *AccountPurgercron_PurgeAccountData_Call) Run(run func(ctx context.Context, accountId string)) *AccountPurgercron_PurgeAccountData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountPurgercron_PurgeAccountData_Call) Return(err error) *AccountPurgercron_PurgeAccountData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountPurgercron_PurgeAccountData_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *AccountPurgercron_PurgeAccountData_Call {
	_c.Call.Return(run)
	return _c
}
