// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bytes"

	mock "github.com/stretchr/testify/mock"
)

// newAsn1Object creates a new instance of asn1Object. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAsn1Object(t interface {
	mock.TestingT
	Cleanup(func())
}) *asn1Object {
	mock := &asn1Object{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// asn1Object is an autogenerated mock type for the asn1Object type
type asn1Object struct {
	mock.Mock
}

type asn1Object_Expecter struct {
	mock *mock.Mock
}

func (_m *asn1Object) EXPECT() *asn1Object_Expecter {
	return &asn1Object_Expecter{mock: &_m.Mock}
}

// EncodeTo provides a mock function for the type asn1Object
func (_mock *asn1Object) EncodeTo(writer *bytes.Buffer) error {
	ret := _mock.Called(writer)

	if len(ret) == 0 {
		panic("no return value specified for EncodeTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*bytes.Buffer) error); ok {
		r0 = returnFunc(writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// asn1Object_EncodeTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeTo'
type asn1Object_EncodeTo_Call struct {
	*mock.Call
}

// EncodeTo is a helper method to define mock.On call
//   - writer *bytes.Buffer
func (_e *asn1Object_Expecter) EncodeTo(writer interface{}) *asn1Object_EncodeTo_Call {
	return &asn1Object_EncodeTo_Call{Call: _e.mock.On("EncodeTo", writer)}
}

func (_c *asn1Object_EncodeTo_Call) Run(run func(writer *bytes.Buffer)) *asn1Object_EncodeTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bytes.Buffer
		if args[0] != nil {
			arg0 = args[0].(*bytes.Buffer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *asn1Object_EncodeTo_Call) Return(err error) *asn1Object_EncodeTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *asn1Object_EncodeTo_Call) RunAndReturn(run func(writer *bytes.Buffer) error) *asn1Object_EncodeTo_Call {
	_c.Call.Return(run)
	return _c
}
