// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ivpn/dns/api/internal/geoip"
	mock "github.com/stretchr/testify/mock"
)

// NewClientEnricherprofile creates a new instance of ClientEnricherprofile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientEnricherprofile(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientEnricherprofile {
	mock := &ClientEnricherprofile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientEnricherprofile is an autogenerated mock type for the ClientEnricher type
type ClientEnricherprofile struct {
	mock.Mock
}

type ClientEnricherprofile_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientEnricherprofile) EXPECT() *ClientEnricherprofile_Expecter {
	return &ClientEnricherprofile_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type ClientEnricherprofile
func (_mock *ClientEnricherprofile) Lookup(ip string) geoip.Info {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 geoip.Info
	if returnFunc, ok := ret.Get(0).(func(string) geoip.Info); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(geoip.Info)
	}
	return r0
}

// ClientEnricherprofile_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type ClientEnricherprofile_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ip string
func (_e *ClientEnricherprofile_Expecter) Lookup(ip interface{}) *ClientEnricherprofile_Lookup_Call {
	return &ClientEnricherprofile_Lookup_Call{Call: _e.mock.On("Lookup", ip)}
}

func (_c *ClientEnricherprofile_Lookup_Call) Run(run func(ip string)) *ClientEnricherprofile_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientEnricherprofile_Lookup_Call) Return(info geoip.Info) *ClientEnricherprofile_Lookup_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *ClientEnricherprofile_Lookup_Call) RunAndReturn(run func(ip string) geoip.Info) *ClientEnricherprofile_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
