// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/api/requests"
	"github.com/ivpn/dns/api/api/responses"
	mock "github.com/stretchr/testify/mock"
)

// NewDNSStampServicerdnsstamp creates a new instance of DNSStampServicerdnsstamp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDNSStampServicerdnsstamp(t interface {
	mock.TestingT
	Cleanup(func())
}) *DNSStampServicerdnsstamp {
	mock := &DNSStampServicerdnsstamp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DNSStampServicerdnsstamp is an autogenerated mock type for the DNSStampServicer type
type DNSStampServicerdnsstamp struct {
	mock.Mock
}

type DNSStampServicerdnsstamp_Expecter struct {
	mock *mock.Mock
}

func (_m *DNSStampServicerdnsstamp) EXPECT() *DNSStampServicerdnsstamp_Expecter {
	return &DNSStampServicerdnsstamp_Expecter{mock: &_m.Mock}
}

// GenerateStamps provides a mock function for the type DNSStampServicerdnsstamp
func (_mock *DNSStampServicerdnsstamp) GenerateStamps(ctx context.Context, req requests.DNSStampReq) (responses.DNSStampResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateStamps")
	}

	var r0 responses.DNSStampResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.DNSStampReq) (responses.DNSStampResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.DNSStampReq) responses.DNSStampResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(responses.DNSStampResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, requests.DNSStampReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DNSStampServicerdnsstamp_GenerateStamps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateStamps'
type DNSStampServicerdnsstamp_GenerateStamps_Call struct {
	*mock.Call
}

// GenerateStamps is a helper method to define mock.On call
//   - ctx context.Context
//   - req requests.DNSStampReq
func (_e *DNSStampServicerdnsstamp_Expecter) GenerateStamps(ctx interface{}, req interface{}) *DNSStampServicerdnsstamp_GenerateStamps_Call {
	return &DNSStampServicerdnsstamp_GenerateStamps_Call{Call: _e.mock.On("GenerateStamps", ctx, req)}
}

func (_c *DNSStampServicerdnsstamp_GenerateStamps_Call) Run(run func(ctx context.Context, req requests.DNSStampReq)) *DNSStampServicerdnsstamp_GenerateStamps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 requests.DNSStampReq
		if args[1] != nil {
			arg1 = args[1].(requests.DNSStampReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DNSStampServicerdnsstamp_GenerateStamps_Call) Return(dNSStampResponse responses.DNSStampResponse, err error) *DNSStampServicerdnsstamp_GenerateStamps_Call {
	_c.Call.Return(dNSStampResponse, err)
	return _c
}

func (_c *DNSStampServicerdnsstamp_GenerateStamps_Call) RunAndReturn(run func(ctx context.Context, req requests.DNSStampReq) (responses.DNSStampResponse, error)) *DNSStampServicerdnsstamp_GenerateStamps_Call {
	_c.Call.Return(run)
	return _c
}
