// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMfaVerifierreauth creates a new instance of MfaVerifierreauth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMfaVerifierreauth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MfaVerifierreauth {
	mock := &MfaVerifierreauth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MfaVerifierreauth is an autogenerated mock type for the MfaVerifier type
type MfaVerifierreauth struct {
	mock.Mock
}

type MfaVerifierreauth_Expecter struct {
	mock *mock.Mock
}

func (_m *MfaVerifierreauth) EXPECT() *MfaVerifierreauth_Expecter {
	return &MfaVerifierreauth_Expecter{mock: &_m.Mock}
}

// MfaCheck provides a mock function for the type MfaVerifierreauth
func (_mock *MfaVerifierreauth) MfaCheck(ctx context.Context, acc *model.Account, mfa *model.MfaData) error {
	ret := _mock.Called(ctx, acc, mfa)

	if len(ret) == 0 {
		panic("no return value specified for MfaCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account, *model.MfaData) error); ok {
		r0 = returnFunc(ctx, acc, mfa)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MfaVerifierreauth_MfaCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MfaCheck'
type MfaVerifierreauth_MfaCheck_Call struct {
	*mock.Call
}

// MfaCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *model.Account
//   - mfa *model.MfaData
func (_e *MfaVerifierreauth_Expecter) MfaCheck(ctx interface{}, acc interface{}, mfa interface{}) *MfaVerifierreauth_MfaCheck_Call {
	return &MfaVerifierreauth_MfaCheck_Call{Call: _e.mock.On("MfaCheck", ctx, acc, mfa)}
}

func (_c *MfaVerifierreauth_MfaCheck_Call) Run(run func(ctx context.Context, acc *model.Account, mfa *model.MfaData)) *MfaVerifierreauth_MfaCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		var arg2 *model.MfaData
		if args[2] != nil {
			arg2 = args[2].(*model.MfaData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MfaVerifierreauth_MfaCheck_Call) Return(err error) *MfaVerifierreauth_MfaCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MfaVerifierreauth_MfaCheck_Call) RunAndReturn(run func(ctx context.Context, acc *model.Account, mfa *model.MfaData) error) *MfaVerifierreauth_MfaCheck_Call {
	_c.Call.Return(run)
	return _c
}
