// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileRepository creates a new instance of ProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepository {
	mock := &ProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileRepository is an autogenerated mock type for the ProfileRepository type
type ProfileRepository struct {
	mock.Mock
}

type ProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileRepository) EXPECT() *ProfileRepository_Expecter {
	return &ProfileRepository_Expecter{mock: &_m.Mock}
}

// CreateCustomRules provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) CreateCustomRules(ctx context.Context, profileId string, rules []*model.CustomRule) error {
	ret := _mock.Called(ctx, profileId, rules)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*model.CustomRule) error); ok {
		r0 = returnFunc(ctx, profileId, rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_CreateCustomRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomRules'
type ProfileRepository_CreateCustomRules_Call struct {
	*mock.Call
}

// CreateCustomRules is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - rules []*model.CustomRule
func (_e *ProfileRepository_Expecter) CreateCustomRules(ctx interface{}, profileId interface{}, rules interface{}) *ProfileRepository_CreateCustomRules_Call {
	return &ProfileRepository_CreateCustomRules_Call{Call: _e.mock.On("CreateCustomRules", ctx, profileId, rules)}
}

func (_c *ProfileRepository_CreateCustomRules_Call) Run(run func(ctx context.Context, profileId string, rules []*model.CustomRule)) *ProfileRepository_CreateCustomRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*model.CustomRule
		if args[2] != nil {
			arg2 = args[2].([]*model.CustomRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_CreateCustomRules_Call) Return(err error) *ProfileRepository_CreateCustomRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_CreateCustomRules_Call) RunAndReturn(run func(ctx context.Context, profileId string, rules []*model.CustomRule) error) *ProfileRepository_CreateCustomRules_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfile provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) CreateProfile(ctx context.Context, profile *model.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type ProfileRepository_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.Profile
func (_e *ProfileRepository_Expecter) CreateProfile(ctx interface{}, profile interface{}) *ProfileRepository_CreateProfile_Call {
	return &ProfileRepository_CreateProfile_Call{Call: _e.mock.On("CreateProfile", ctx, profile)}
}

func (_c *ProfileRepository_CreateProfile_Call) Run(run func(ctx context.Context, profile *model.Profile)) *ProfileRepository_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Profile
		if args[1] != nil {
			arg1 = args[1].(*model.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepository_CreateProfile_Call) Return(err error) *ProfileRepository_CreateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_CreateProfile_Call) RunAndReturn(run func(ctx context.Context, profile *model.Profile) error) *ProfileRepository_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfileById provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) DeleteProfileById(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_DeleteProfileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfileById'
type ProfileRepository_DeleteProfileById_Call struct {
	*mock.Call
}

// DeleteProfileById is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *ProfileRepository_Expecter) DeleteProfileById(ctx interface{}, profileId interface{}) *ProfileRepository_DeleteProfileById_Call {
	return &ProfileRepository_DeleteProfileById_Call{Call: _e.mock.On("DeleteProfileById", ctx, profileId)}
}

func (_c *ProfileRepository_DeleteProfileById_Call) Run(run func(ctx context.Context, profileId string)) *ProfileRepository_DeleteProfileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepository_DeleteProfileById_Call) Return(err error) *ProfileRepository_DeleteProfileById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_DeleteProfileById_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *ProfileRepository_DeleteProfileById_Call {
	_c.Call.Return(run)
	return _c
}

// DisableBlocklists provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) DisableBlocklists(ctx context.Context, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for DisableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_DisableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableBlocklists'
type ProfileRepository_DisableBlocklists_Call struct {
	*mock.Call
}

// DisableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds []string
func (_e *ProfileRepository_Expecter) DisableBlocklists(ctx interface{}, profileId interface{}, blocklistIds interface{}) *ProfileRepository_DisableBlocklists_Call {
	return &ProfileRepository_DisableBlocklists_Call{Call: _e.mock.On("DisableBlocklists", ctx, profileId, blocklistIds)}
}

func (_c *ProfileRepository_DisableBlocklists_Call) Run(run func(ctx context.Context, profileId string, blocklistIds []string)) *ProfileRepository_DisableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_DisableBlocklists_Call) Return(err error) *ProfileRepository_DisableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_DisableBlocklists_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds []string) error) *ProfileRepository_DisableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// DisableServices provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) DisableServices(ctx context.Context, profileId string, serviceIds []string) error {
	ret := _mock.Called(ctx, profileId, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for DisableServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, serviceIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_DisableServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableServices'
type ProfileRepository_DisableServices_Call struct {
	*mock.Call
}

// DisableServices is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - serviceIds []string
func (_e *ProfileRepository_Expecter) DisableServices(ctx interface{}, profileId interface{}, serviceIds interface{}) *ProfileRepository_DisableServices_Call {
	return &ProfileRepository_DisableServices_Call{Call: _e.mock.On("DisableServices", ctx, profileId, serviceIds)}
}

func (_c *ProfileRepository_DisableServices_Call) Run(run func(ctx context.Context, profileId string, serviceIds []string)) *ProfileRepository_DisableServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_DisableServices_Call) Return(err error) *ProfileRepository_DisableServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_DisableServices_Call) RunAndReturn(run func(ctx context.Context, profileId string, serviceIds []string) error) *ProfileRepository_DisableServices_Call {
	_c.Call.Return(run)
	return _c
}

// EnableBlocklists provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) EnableBlocklists(ctx context.Context, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for EnableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_EnableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableBlocklists'
type ProfileRepository_EnableBlocklists_Call struct {
	*mock.Call
}

// EnableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds []string
func (_e *ProfileRepository_Expecter) EnableBlocklists(ctx interface{}, profileId interface{}, blocklistIds interface{}) *ProfileRepository_EnableBlocklists_Call {
	return &ProfileRepository_EnableBlocklists_Call{Call: _e.mock.On("EnableBlocklists", ctx, profileId, blocklistIds)}
}

func (_c *ProfileRepository_EnableBlocklists_Call) Run(run func(ctx context.Context, profileId string, blocklistIds []string)) *ProfileRepository_EnableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_EnableBlocklists_Call) Return(err error) *ProfileRepository_EnableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_EnableBlocklists_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds []string) error) *ProfileRepository_EnableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// EnableServices provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) EnableServices(ctx context.Context, profileId string, serviceIds []string) error {
	ret := _mock.Called(ctx, profileId, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for EnableServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, serviceIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_EnableServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableServices'
type ProfileRepository_EnableServices_Call struct {
	*mock.Call
}

// EnableServices is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - serviceIds []string
func (_e *ProfileRepository_Expecter) EnableServices(ctx interface{}, profileId interface{}, serviceIds interface{}) *ProfileRepository_EnableServices_Call {
	return &ProfileRepository_EnableServices_Call{Call: _e.mock.On("EnableServices", ctx, profileId, serviceIds)}
}

func (_c *ProfileRepository_EnableServices_Call) Run(run func(ctx context.Context, profileId string, serviceIds []string)) *ProfileRepository_EnableServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_EnableServices_Call) Return(err error) *ProfileRepository_EnableServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_EnableServices_Call) RunAndReturn(run func(ctx context.Context, profileId string, serviceIds []string) error) *ProfileRepository_EnableServices_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileById provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) GetProfileById(ctx context.Context, profileId string) (*model.Profile, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileById")
	}

	var r0 *model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Profile, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Profile); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileRepository_GetProfileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileById'
type ProfileRepository_GetProfileById_Call struct {
	*mock.Call
}

// GetProfileById is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *ProfileRepository_Expecter) GetProfileById(ctx interface{}, profileId interface{}) *ProfileRepository_GetProfileById_Call {
	return &ProfileRepository_GetProfileById_Call{Call: _e.mock.On("GetProfileById", ctx, profileId)}
}

func (_c *ProfileRepository_GetProfileById_Call) Run(run func(ctx context.Context, profileId string)) *ProfileRepository_GetProfileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepository_GetProfileById_Call) Return(profile *model.Profile, err error) *ProfileRepository_GetProfileById_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *ProfileRepository_GetProfileById_Call) RunAndReturn(run func(ctx context.Context, profileId string) (*model.Profile, error)) *ProfileRepository_GetProfileById_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfilesByAccountId provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) GetProfilesByAccountId(ctx context.Context, accountId string) ([]model.Profile, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilesByAccountId")
	}

	var r0 []model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Profile, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Profile); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileRepository_GetProfilesByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilesByAccountId'
type ProfileRepository_GetProfilesByAccountId_Call struct {
	*mock.Call
}

// GetProfilesByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *ProfileRepository_Expecter) GetProfilesByAccountId(ctx interface{}, accountId interface{}) *ProfileRepository_GetProfilesByAccountId_Call {
	return &ProfileRepository_GetProfilesByAccountId_Call{Call: _e.mock.On("GetProfilesByAccountId", ctx, accountId)}
}

func (_c *ProfileRepository_GetProfilesByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *ProfileRepository_GetProfilesByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepository_GetProfilesByAccountId_Call) Return(profiles []model.Profile, err error) *ProfileRepository_GetProfilesByAccountId_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *ProfileRepository_GetProfilesByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) ([]model.Profile, error)) *ProfileRepository_GetProfilesByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignCustomRuleGroup provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) ReassignCustomRuleGroup(ctx context.Context, profileId string, from string, to string) error {
	ret := _mock.Called(ctx, profileId, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ReassignCustomRuleGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, profileId, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_ReassignCustomRuleGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignCustomRuleGroup'
type ProfileRepository_ReassignCustomRuleGroup_Call struct {
	*mock.Call
}

// ReassignCustomRuleGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - from string
//   - to string
func (_e *ProfileRepository_Expecter) ReassignCustomRuleGroup(ctx interface{}, profileId interface{}, from interface{}, to interface{}) *ProfileRepository_ReassignCustomRuleGroup_Call {
	return &ProfileRepository_ReassignCustomRuleGroup_Call{Call: _e.mock.On("ReassignCustomRuleGroup", ctx, profileId, from, to)}
}

func (_c *ProfileRepository_ReassignCustomRuleGroup_Call) Run(run func(ctx context.Context, profileId string, from string, to string)) *ProfileRepository_ReassignCustomRuleGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileRepository_ReassignCustomRuleGroup_Call) Return(err error) *ProfileRepository_ReassignCustomRuleGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_ReassignCustomRuleGroup_Call) RunAndReturn(run func(ctx context.Context, profileId string, from string, to string) error) *ProfileRepository_ReassignCustomRuleGroup_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCustomRules provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) RemoveCustomRules(ctx context.Context, profileId string, ruleIds []string) error {
	ret := _mock.Called(ctx, profileId, ruleIds)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCustomRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, ruleIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_RemoveCustomRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCustomRules'
type ProfileRepository_RemoveCustomRules_Call struct {
	*mock.Call
}

// RemoveCustomRules is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - ruleIds []string
func (_e *ProfileRepository_Expecter) RemoveCustomRules(ctx interface{}, profileId interface{}, ruleIds interface{}) *ProfileRepository_RemoveCustomRules_Call {
	return &ProfileRepository_RemoveCustomRules_Call{Call: _e.mock.On("RemoveCustomRules", ctx, profileId, ruleIds)}
}

func (_c *ProfileRepository_RemoveCustomRules_Call) Run(run func(ctx context.Context, profileId string, ruleIds []string)) *ProfileRepository_RemoveCustomRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_RemoveCustomRules_Call) Return(err error) *ProfileRepository_RemoveCustomRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_RemoveCustomRules_Call) RunAndReturn(run func(ctx context.Context, profileId string, ruleIds []string) error) *ProfileRepository_RemoveCustomRules_Call {
	_c.Call.Return(run)
	return _c
}

// SetCustomRuleGroups provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) SetCustomRuleGroups(ctx context.Context, profileId string, groups map[string]string) error {
	ret := _mock.Called(ctx, profileId, groups)

	if len(ret) == 0 {
		panic("no return value specified for SetCustomRuleGroups")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, profileId, groups)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_SetCustomRuleGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCustomRuleGroups'
type ProfileRepository_SetCustomRuleGroups_Call struct {
	*mock.Call
}

// SetCustomRuleGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - groups map[string]string
func (_e *ProfileRepository_Expecter) SetCustomRuleGroups(ctx interface{}, profileId interface{}, groups interface{}) *ProfileRepository_SetCustomRuleGroups_Call {
	return &ProfileRepository_SetCustomRuleGroups_Call{Call: _e.mock.On("SetCustomRuleGroups", ctx, profileId, groups)}
}

func (_c *ProfileRepository_SetCustomRuleGroups_Call) Run(run func(ctx context.Context, profileId string, groups map[string]string)) *ProfileRepository_SetCustomRuleGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_SetCustomRuleGroups_Call) Return(err error) *ProfileRepository_SetCustomRuleGroups_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_SetCustomRuleGroups_Call) RunAndReturn(run func(ctx context.Context, profileId string, groups map[string]string) error) *ProfileRepository_SetCustomRuleGroups_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) Update(ctx context.Context, profileId string, profile *model.Profile) error {
	ret := _mock.Called(ctx, profileId, profile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Profile) error); ok {
		r0 = returnFunc(ctx, profileId, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - profile *model.Profile
func (_e *ProfileRepository_Expecter) Update(ctx interface{}, profileId interface{}, profile interface{}) *ProfileRepository_Update_Call {
	return &ProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, profileId, profile)}
}

func (_c *ProfileRepository_Update_Call) Run(run func(ctx context.Context, profileId string, profile *model.Profile)) *ProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Profile
		if args[2] != nil {
			arg2 = args[2].(*model.Profile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_Update_Call) Return(err error) *ProfileRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, profileId string, profile *model.Profile) error) *ProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomRule provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) UpdateCustomRule(ctx context.Context, profileId string, rule *model.CustomRule) error {
	ret := _mock.Called(ctx, profileId, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.CustomRule) error); ok {
		r0 = returnFunc(ctx, profileId, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_UpdateCustomRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomRule'
type ProfileRepository_UpdateCustomRule_Call struct {
	*mock.Call
}

// UpdateCustomRule is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - rule *model.CustomRule
func (_e *ProfileRepository_Expecter) UpdateCustomRule(ctx interface{}, profileId interface{}, rule interface{}) *ProfileRepository_UpdateCustomRule_Call {
	return &ProfileRepository_UpdateCustomRule_Call{Call: _e.mock.On("UpdateCustomRule", ctx, profileId, rule)}
}

func (_c *ProfileRepository_UpdateCustomRule_Call) Run(run func(ctx context.Context, profileId string, rule *model.CustomRule)) *ProfileRepository_UpdateCustomRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.CustomRule
		if args[2] != nil {
			arg2 = args[2].(*model.CustomRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_UpdateCustomRule_Call) Return(err error) *ProfileRepository_UpdateCustomRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_UpdateCustomRule_Call) RunAndReturn(run func(ctx context.Context, profileId string, rule *model.CustomRule) error) *ProfileRepository_UpdateCustomRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomRulesOrder provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) UpdateCustomRulesOrder(ctx context.Context, profileId string, idToOrder map[string]int) error {
	ret := _mock.Called(ctx, profileId, idToOrder)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomRulesOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]int) error); ok {
		r0 = returnFunc(ctx, profileId, idToOrder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_UpdateCustomRulesOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomRulesOrder'
type ProfileRepository_UpdateCustomRulesOrder_Call struct {
	*mock.Call
}

// UpdateCustomRulesOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - idToOrder map[string]int
func (_e *ProfileRepository_Expecter) UpdateCustomRulesOrder(ctx interface{}, profileId interface{}, idToOrder interface{}) *ProfileRepository_UpdateCustomRulesOrder_Call {
	return &ProfileRepository_UpdateCustomRulesOrder_Call{Call: _e.mock.On("UpdateCustomRulesOrder", ctx, profileId, idToOrder)}
}

func (_c *ProfileRepository_UpdateCustomRulesOrder_Call) Run(run func(ctx context.Context, profileId string, idToOrder map[string]int)) *ProfileRepository_UpdateCustomRulesOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]int
		if args[2] != nil {
			arg2 = args[2].(map[string]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_UpdateCustomRulesOrder_Call) Return(err error) *ProfileRepository_UpdateCustomRulesOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_UpdateCustomRulesOrder_Call) RunAndReturn(run func(ctx context.Context, profileId string, idToOrder map[string]int) error) *ProfileRepository_UpdateCustomRulesOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function for the type ProfileRepository
func (_mock *ProfileRepository) UpdateSettings(ctx context.Context, profileId string, settings *model.ProfileSettings) error {
	ret := _mock.Called(ctx, profileId, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ProfileSettings) error); ok {
		r0 = returnFunc(ctx, profileId, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileRepository_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type ProfileRepository_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - settings *model.ProfileSettings
func (_e *ProfileRepository_Expecter) UpdateSettings(ctx interface{}, profileId interface{}, settings interface{}) *ProfileRepository_UpdateSettings_Call {
	return &ProfileRepository_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", ctx, profileId, settings)}
}

func (_c *ProfileRepository_UpdateSettings_Call) Run(run func(ctx context.Context, profileId string, settings *model.ProfileSettings)) *ProfileRepository_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ProfileSettings
		if args[2] != nil {
			arg2 = args[2].(*model.ProfileSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepository_UpdateSettings_Call) Return(err error) *ProfileRepository_UpdateSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileRepository_UpdateSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string, settings *model.ProfileSettings) error) *ProfileRepository_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}
