// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileStatisticsReaderstatistics creates a new instance of ProfileStatisticsReaderstatistics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileStatisticsReaderstatistics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileStatisticsReaderstatistics {
	mock := &ProfileStatisticsReaderstatistics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileStatisticsReaderstatistics is an autogenerated mock type for the ProfileStatisticsReader type
type ProfileStatisticsReaderstatistics struct {
	mock.Mock
}

type ProfileStatisticsReaderstatistics_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileStatisticsReaderstatistics) EXPECT() *ProfileStatisticsReaderstatistics_Expecter {
	return &ProfileStatisticsReaderstatistics_Expecter{mock: &_m.Mock}
}

// GetProfilesStatisticsSettings provides a mock function for the type ProfileStatisticsReaderstatistics
func (_mock *ProfileStatisticsReaderstatistics) GetProfilesStatisticsSettings(ctx context.Context, profileIds []string) (map[string]*model.StatisticsSettings, error) {
	ret := _mock.Called(ctx, profileIds)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilesStatisticsSettings")
	}

	var r0 map[string]*model.StatisticsSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]*model.StatisticsSettings, error)); ok {
		return returnFunc(ctx, profileIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]*model.StatisticsSettings); ok {
		r0 = returnFunc(ctx, profileIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.StatisticsSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, profileIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilesStatisticsSettings'
type ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call struct {
	*mock.Call
}

// GetProfilesStatisticsSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileIds []string
func (_e *ProfileStatisticsReaderstatistics_Expecter) GetProfilesStatisticsSettings(ctx interface{}, profileIds interface{}) *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call {
	return &ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call{Call: _e.mock.On("GetProfilesStatisticsSettings", ctx, profileIds)}
}

func (_c *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call) Run(run func(ctx context.Context, profileIds []string)) *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call) Return(stringToStatisticsSettings map[string]*model.StatisticsSettings, err error) *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call {
	_c.Call.Return(stringToStatisticsSettings, err)
	return _c
}

func (_c *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call) RunAndReturn(run func(ctx context.Context, profileIds []string) (map[string]*model.StatisticsSettings, error)) *ProfileStatisticsReaderstatistics_GetProfilesStatisticsSettings_Call {
	_c.Call.Return(run)
	return _c
}
