// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryLogsRepository creates a new instance of QueryLogsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryLogsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryLogsRepository {
	mock := &QueryLogsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryLogsRepository is an autogenerated mock type for the QueryLogsRepository type
type QueryLogsRepository struct {
	mock.Mock
}

type QueryLogsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryLogsRepository) EXPECT() *QueryLogsRepository_Expecter {
	return &QueryLogsRepository_Expecter{mock: &_m.Mock}
}

// DeleteQueryLogs provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) DeleteQueryLogs(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueryLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueryLogsRepository_DeleteQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueryLogs'
type QueryLogsRepository_DeleteQueryLogs_Call struct {
	*mock.Call
}

// DeleteQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *QueryLogsRepository_Expecter) DeleteQueryLogs(ctx interface{}, profileId interface{}) *QueryLogsRepository_DeleteQueryLogs_Call {
	return &QueryLogsRepository_DeleteQueryLogs_Call{Call: _e.mock.On("DeleteQueryLogs", ctx, profileId)}
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) Run(run func(ctx context.Context, profileId string)) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) Return(err error) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogDevices provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) GetQueryLogDevices(ctx context.Context, profileId string, retention model.Retention) ([]model.QueryLogDevice, error) {
	ret := _mock.Called(ctx, profileId, retention)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogDevices")
	}

	var r0 []model.QueryLogDevice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention) ([]model.QueryLogDevice, error)); ok {
		return returnFunc(ctx, profileId, retention)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention) []model.QueryLogDevice); ok {
		r0 = returnFunc(ctx, profileId, retention)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLogDevice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention) error); ok {
		r1 = returnFunc(ctx, profileId, retention)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_GetQueryLogDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogDevices'
type QueryLogsRepository_GetQueryLogDevices_Call struct {
	*mock.Call
}

// GetQueryLogDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
func (_e *QueryLogsRepository_Expecter) GetQueryLogDevices(ctx interface{}, profileId interface{}, retention interface{}) *QueryLogsRepository_GetQueryLogDevices_Call {
	return &QueryLogsRepository_GetQueryLogDevices_Call{Call: _e.mock.On("GetQueryLogDevices", ctx, profileId, retention)}
}

func (_c *QueryLogsRepository_GetQueryLogDevices_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention)) *QueryLogsRepository_GetQueryLogDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogDevices_Call) Return(queryLogDevices []model.QueryLogDevice, err error) *QueryLogsRepository_GetQueryLogDevices_Call {
	_c.Call.Return(queryLogDevices, err)
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogDevices_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention) ([]model.QueryLogDevice, error)) *QueryLogsRepository_GetQueryLogDevices_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogTopClients provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) GetQueryLogTopClients(ctx context.Context, profileId string, retention model.Retention, timespanHours int, limit int) ([]model.QueryLogTopClient, error) {
	ret := _mock.Called(ctx, profileId, retention, timespanHours, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogTopClients")
	}

	var r0 []model.QueryLogTopClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, int, int) ([]model.QueryLogTopClient, error)); ok {
		return returnFunc(ctx, profileId, retention, timespanHours, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, int, int) []model.QueryLogTopClient); ok {
		r0 = returnFunc(ctx, profileId, retention, timespanHours, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLogTopClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, timespanHours, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_GetQueryLogTopClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogTopClients'
type QueryLogsRepository_GetQueryLogTopClients_Call struct {
	*mock.Call
}

// GetQueryLogTopClients is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - timespanHours int
//   - limit int
func (_e *QueryLogsRepository_Expecter) GetQueryLogTopClients(ctx interface{}, profileId interface{}, retention interface{}, timespanHours interface{}, limit interface{}) *QueryLogsRepository_GetQueryLogTopClients_Call {
	return &QueryLogsRepository_GetQueryLogTopClients_Call{Call: _e.mock.On("GetQueryLogTopClients", ctx, profileId, retention, timespanHours, limit)}
}

func (_c *QueryLogsRepository_GetQueryLogTopClients_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, timespanHours int, limit int)) *QueryLogsRepository_GetQueryLogTopClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogTopClients_Call) Return(queryLogTopClients []model.QueryLogTopClient, err error) *QueryLogsRepository_GetQueryLogTopClients_Call {
	_c.Call.Return(queryLogTopClients, err)
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogTopClients_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, timespanHours int, limit int) ([]model.QueryLogTopClient, error)) *QueryLogsRepository_GetQueryLogTopClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogTopDomains provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) GetQueryLogTopDomains(ctx context.Context, profileId string, retention model.Retention, status string, timespanHours int, limit int) ([]model.QueryLogTopDomain, error) {
	ret := _mock.Called(ctx, profileId, retention, status, timespanHours, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogTopDomains")
	}

	var r0 []model.QueryLogTopDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, int) ([]model.QueryLogTopDomain, error)); ok {
		return returnFunc(ctx, profileId, retention, status, timespanHours, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, int) []model.QueryLogTopDomain); ok {
		r0 = returnFunc(ctx, profileId, retention, status, timespanHours, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLogTopDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, string, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, status, timespanHours, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_GetQueryLogTopDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogTopDomains'
type QueryLogsRepository_GetQueryLogTopDomains_Call struct {
	*mock.Call
}

// GetQueryLogTopDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - status string
//   - timespanHours int
//   - limit int
func (_e *QueryLogsRepository_Expecter) GetQueryLogTopDomains(ctx interface{}, profileId interface{}, retention interface{}, status interface{}, timespanHours interface{}, limit interface{}) *QueryLogsRepository_GetQueryLogTopDomains_Call {
	return &QueryLogsRepository_GetQueryLogTopDomains_Call{Call: _e.mock.On("GetQueryLogTopDomains", ctx, profileId, retention, status, timespanHours, limit)}
}

func (_c *QueryLogsRepository_GetQueryLogTopDomains_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespanHours int, limit int)) *QueryLogsRepository_GetQueryLogTopDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogTopDomains_Call) Return(queryLogTopDomains []model.QueryLogTopDomain, err error) *QueryLogsRepository_GetQueryLogTopDomains_Call {
	_c.Call.Return(queryLogTopDomains, err)
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogTopDomains_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespanHours int, limit int) ([]model.QueryLogTopDomain, error)) *QueryLogsRepository_GetQueryLogTopDomains_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogs provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) GetQueryLogs(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, sortBy string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, profileId, retention, status, timespan, deviceId, search, sortBy, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, sortBy, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, sortBy, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, string, int, string, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, sortBy, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_GetQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogs'
type QueryLogsRepository_GetQueryLogs_Call struct {
	*mock.Call
}

// GetQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - status string
//   - timespan int
//   - deviceId string
//   - search string
//   - sortBy string
//   - page int
//   - limit int
func (_e *QueryLogsRepository_Expecter) GetQueryLogs(ctx interface{}, profileId interface{}, retention interface{}, status interface{}, timespan interface{}, deviceId interface{}, search interface{}, sortBy interface{}, page interface{}, limit interface{}) *QueryLogsRepository_GetQueryLogs_Call {
	return &QueryLogsRepository_GetQueryLogs_Call{Call: _e.mock.On("GetQueryLogs", ctx, profileId, retention, status, timespan, deviceId, search, sortBy, page, limit)}
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, sortBy string, page int, limit int)) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		var arg8 int
		if args[8] != nil {
			arg8 = args[8].(int)
		}
		var arg9 int
		if args[9] != nil {
			arg9 = args[9].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, sortBy string, page int, limit int) ([]model.QueryLog, error)) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueryLogProfileIDs provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) ListQueryLogProfileIDs(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListQueryLogProfileIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_ListQueryLogProfileIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueryLogProfileIDs'
type QueryLogsRepository_ListQueryLogProfileIDs_Call struct {
	*mock.Call
}

// ListQueryLogProfileIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QueryLogsRepository_Expecter) ListQueryLogProfileIDs(ctx interface{}) *QueryLogsRepository_ListQueryLogProfileIDs_Call {
	return &QueryLogsRepository_ListQueryLogProfileIDs_Call{Call: _e.mock.On("ListQueryLogProfileIDs", ctx)}
}

func (_c *QueryLogsRepository_ListQueryLogProfileIDs_Call) Run(run func(ctx context.Context)) *QueryLogsRepository_ListQueryLogProfileIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_ListQueryLogProfileIDs_Call) Return(strings []string, err error) *QueryLogsRepository_ListQueryLogProfileIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *QueryLogsRepository_ListQueryLogProfileIDs_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *QueryLogsRepository_ListQueryLogProfileIDs_Call {
	_c.Call.Return(run)
	return _c
}
