// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewReadCachestatistics creates a new instance of ReadCachestatistics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadCachestatistics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadCachestatistics {
	mock := &ReadCachestatistics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReadCachestatistics is an autogenerated mock type for the ReadCache type
type ReadCachestatistics struct {
	mock.Mock
}

type ReadCachestatistics_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadCachestatistics) EXPECT() *ReadCachestatistics_Expecter {
	return &ReadCachestatistics_Expecter{mock: &_m.Mock}
}

// GetStatistics provides a mock function for the type ReadCachestatistics
func (_mock *ReadCachestatistics) GetStatistics(ctx context.Context, profileId string, timespan string) ([]byte, bool, error) {
	ret := _mock.Called(ctx, profileId, timespan)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, bool, error)); ok {
		return returnFunc(ctx, profileId, timespan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, profileId, timespan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, profileId, timespan)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, profileId, timespan)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReadCachestatistics_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type ReadCachestatistics_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - timespan string
func (_e *ReadCachestatistics_Expecter) GetStatistics(ctx interface{}, profileId interface{}, timespan interface{}) *ReadCachestatistics_GetStatistics_Call {
	return &ReadCachestatistics_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, profileId, timespan)}
}

func (_c *ReadCachestatistics_GetStatistics_Call) Run(run func(ctx context.Context, profileId string, timespan string)) *ReadCachestatistics_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReadCachestatistics_GetStatistics_Call) Return(payload []byte, found bool, err error) *ReadCachestatistics_GetStatistics_Call {
	_c.Call.Return(payload, found, err)
	return _c
}

func (_c *ReadCachestatistics_GetStatistics_Call) RunAndReturn(run func(ctx context.Context, profileId string, timespan string) ([]byte, bool, error)) *ReadCachestatistics_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateStatistics provides a mock function for the type ReadCachestatistics
func (_mock *ReadCachestatistics) InvalidateStatistics(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateStatistics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReadCachestatistics_InvalidateStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateStatistics'
type ReadCachestatistics_InvalidateStatistics_Call struct {
	*mock.Call
}

// InvalidateStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *ReadCachestatistics_Expecter) InvalidateStatistics(ctx interface{}, profileId interface{}) *ReadCachestatistics_InvalidateStatistics_Call {
	return &ReadCachestatistics_InvalidateStatistics_Call{Call: _e.mock.On("InvalidateStatistics", ctx, profileId)}
}

func (_c *ReadCachestatistics_InvalidateStatistics_Call) Run(run func(ctx context.Context, profileId string)) *ReadCachestatistics_InvalidateStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReadCachestatistics_InvalidateStatistics_Call) Return(err error) *ReadCachestatistics_InvalidateStatistics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReadCachestatistics_InvalidateStatistics_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *ReadCachestatistics_InvalidateStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatistics provides a mock function for the type ReadCachestatistics
func (_mock *ReadCachestatistics) SetStatistics(ctx context.Context, profileId string, timespan string, payload []byte) error {
	ret := _mock.Called(ctx, profileId, timespan, payload)

	if len(ret) == 0 {
		panic("no return value specified for SetStatistics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, profileId, timespan, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReadCachestatistics_SetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatistics'
type ReadCachestatistics_SetStatistics_Call struct {
	*mock.Call
}

// SetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - timespan string
//   - payload []byte
func (_e *ReadCachestatistics_Expecter) SetStatistics(ctx interface{}, profileId interface{}, timespan interface{}, payload interface{}) *ReadCachestatistics_SetStatistics_Call {
	return &ReadCachestatistics_SetStatistics_Call{Call: _e.mock.On("SetStatistics", ctx, profileId, timespan, payload)}
}

func (_c *ReadCachestatistics_SetStatistics_Call) Run(run func(ctx context.Context, profileId string, timespan string, payload []byte)) *ReadCachestatistics_SetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReadCachestatistics_SetStatistics_Call) Return(err error) *ReadCachestatistics_SetStatistics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReadCachestatistics_SetStatistics_Call) RunAndReturn(run func(ctx context.Context, profileId string, timespan string, payload []byte) error) *ReadCachestatistics_SetStatistics_Call {
	_c.Call.Return(run)
	return _c
}
