// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ivpn/dns/libs/servicescatalog"
	mock "github.com/stretchr/testify/mock"
)

// newServicesCatalogReader creates a new instance of servicesCatalogReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newServicesCatalogReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *servicesCatalogReader {
	mock := &servicesCatalogReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// servicesCatalogReader is an autogenerated mock type for the servicesCatalogReader type
type servicesCatalogReader struct {
	mock.Mock
}

type servicesCatalogReader_Expecter struct {
	mock *mock.Mock
}

func (_m *servicesCatalogReader) EXPECT() *servicesCatalogReader_Expecter {
	return &servicesCatalogReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type servicesCatalogReader
func (_mock *servicesCatalogReader) Get() (*servicescatalog.Catalog, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *servicescatalog.Catalog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*servicescatalog.Catalog, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *servicescatalog.Catalog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicescatalog.Catalog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// servicesCatalogReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type servicesCatalogReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *servicesCatalogReader_Expecter) Get() *servicesCatalogReader_Get_Call {
	return &servicesCatalogReader_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *servicesCatalogReader_Get_Call) Run(run func()) *servicesCatalogReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *servicesCatalogReader_Get_Call) Return(catalog *servicescatalog.Catalog, err error) *servicesCatalogReader_Get_Call {
	_c.Call.Return(catalog, err)
	return _c
}

func (_c *servicesCatalogReader_Get_Call) RunAndReturn(run func() (*servicescatalog.Catalog, error)) *servicesCatalogReader_Get_Call {
	_c.Call.Return(run)
	return _c
}
