// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ivpn/dns/libs/servicescatalog"
	mock "github.com/stretchr/testify/mock"
)

// NewServicesCatalogReaderprofile creates a new instance of ServicesCatalogReaderprofile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicesCatalogReaderprofile(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicesCatalogReaderprofile {
	mock := &ServicesCatalogReaderprofile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServicesCatalogReaderprofile is an autogenerated mock type for the ServicesCatalogReader type
type ServicesCatalogReaderprofile struct {
	mock.Mock
}

type ServicesCatalogReaderprofile_Expecter struct {
	mock *mock.Mock
}

func (_m *ServicesCatalogReaderprofile) EXPECT() *ServicesCatalogReaderprofile_Expecter {
	return &ServicesCatalogReaderprofile_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type ServicesCatalogReaderprofile
func (_mock *ServicesCatalogReaderprofile) Get() (*servicescatalog.Catalog, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *servicescatalog.Catalog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*servicescatalog.Catalog, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *servicescatalog.Catalog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicescatalog.Catalog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServicesCatalogReaderprofile_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ServicesCatalogReaderprofile_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *ServicesCatalogReaderprofile_Expecter) Get() *ServicesCatalogReaderprofile_Get_Call {
	return &ServicesCatalogReaderprofile_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *ServicesCatalogReaderprofile_Get_Call) Run(run func()) *ServicesCatalogReaderprofile_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServicesCatalogReaderprofile_Get_Call) Return(catalog *servicescatalog.Catalog, err error) *ServicesCatalogReaderprofile_Get_Call {
	_c.Call.Return(catalog, err)
	return _c
}

func (_c *ServicesCatalogReaderprofile_Get_Call) RunAndReturn(run func() (*servicescatalog.Catalog, error)) *ServicesCatalogReaderprofile_Get_Call {
	_c.Call.Return(run)
	return _c
}
