// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ivpn/dns/api/service/statistics"
	mock "github.com/stretchr/testify/mock"
)

// NewStatisticsPurgeSweepercron creates a new instance of StatisticsPurgeSweepercron. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatisticsPurgeSweepercron(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatisticsPurgeSweepercron {
	mock := &StatisticsPurgeSweepercron{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatisticsPurgeSweepercron is an autogenerated mock type for the StatisticsPurgeSweeper type
type StatisticsPurgeSweepercron struct {
	mock.Mock
}

type StatisticsPurgeSweepercron_Expecter struct {
	mock *mock.Mock
}

func (_m *StatisticsPurgeSweepercron) EXPECT() *StatisticsPurgeSweepercron_Expecter {
	return &StatisticsPurgeSweepercron_Expecter{mock: &_m.Mock}
}

// Sweep provides a mock function for the type StatisticsPurgeSweepercron
func (_mock *StatisticsPurgeSweepercron) Sweep(ctx context.Context, now time.Time) (statistics.SweepResult, error) {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for Sweep")
	}

	var r0 statistics.SweepResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (statistics.SweepResult, error)); ok {
		return returnFunc(ctx, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) statistics.SweepResult); ok {
		r0 = returnFunc(ctx, now)
	} else {
		r0 = ret.Get(0).(statistics.SweepResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatisticsPurgeSweepercron_Sweep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sweep'
type StatisticsPurgeSweepercron_Sweep_Call struct {
	*mock.Call
}

// Sweep is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *StatisticsPurgeSweepercron_Expecter) Sweep(ctx interface{}, now interface{}) *StatisticsPurgeSweepercron_Sweep_Call {
	return &StatisticsPurgeSweepercron_Sweep_Call{Call: _e.mock.On("Sweep", ctx, now)}
}

func (_c *StatisticsPurgeSweepercron_Sweep_Call) Run(run func(ctx context.Context, now time.Time)) *StatisticsPurgeSweepercron_Sweep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StatisticsPurgeSweepercron_Sweep_Call) Return(sweepResult statistics.SweepResult, err error) *StatisticsPurgeSweepercron_Sweep_Call {
	_c.Call.Return(sweepResult, err)
	return _c
}

func (_c *StatisticsPurgeSweepercron_Sweep_Call) RunAndReturn(run func(ctx context.Context, now time.Time) (statistics.SweepResult, error)) *StatisticsPurgeSweepercron_Sweep_Call {
	_c.Call.Return(run)
	return _c
}
