// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/service/statistics"
	mock "github.com/stretchr/testify/mock"
)

// NewStatisticsReconcilercron creates a new instance of StatisticsReconcilercron. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatisticsReconcilercron(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatisticsReconcilercron {
	mock := &StatisticsReconcilercron{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatisticsReconcilercron is an autogenerated mock type for the StatisticsReconciler type
type StatisticsReconcilercron struct {
	mock.Mock
}

type StatisticsReconcilercron_Expecter struct {
	mock *mock.Mock
}

func (_m *StatisticsReconcilercron) EXPECT() *StatisticsReconcilercron_Expecter {
	return &StatisticsReconcilercron_Expecter{mock: &_m.Mock}
}

// ReconcileStatistics provides a mock function for the type StatisticsReconcilercron
func (_mock *StatisticsReconcilercron) ReconcileStatistics(ctx context.Context) (statistics.StatisticsReconcileResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileStatistics")
	}

	var r0 statistics.StatisticsReconcileResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (statistics.StatisticsReconcileResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) statistics.StatisticsReconcileResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(statistics.StatisticsReconcileResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatisticsReconcilercron_ReconcileStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileStatistics'
type StatisticsReconcilercron_ReconcileStatistics_Call struct {
	*mock.Call
}

// ReconcileStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StatisticsReconcilercron_Expecter) ReconcileStatistics(ctx interface{}) *StatisticsReconcilercron_ReconcileStatistics_Call {
	return &StatisticsReconcilercron_ReconcileStatistics_Call{Call: _e.mock.On("ReconcileStatistics", ctx)}
}

func (_c *StatisticsReconcilercron_ReconcileStatistics_Call) Run(run func(ctx context.Context)) *StatisticsReconcilercron_ReconcileStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatisticsReconcilercron_ReconcileStatistics_Call) Return(statisticsReconcileResult statistics.StatisticsReconcileResult, err error) *StatisticsReconcilercron_ReconcileStatistics_Call {
	_c.Call.Return(statisticsReconcileResult, err)
	return _c
}

func (_c *StatisticsReconcilercron_ReconcileStatistics_Call) RunAndReturn(run func(ctx context.Context) (statistics.StatisticsReconcileResult, error)) *StatisticsReconcilercron_ReconcileStatistics_Call {
	_c.Call.Return(run)
	return _c
}
