// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ivpn/dns/api/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewStatisticsPurgeQueuecache creates a new instance of StatisticsPurgeQueuecache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatisticsPurgeQueuecache(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatisticsPurgeQueuecache {
	mock := &StatisticsPurgeQueuecache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatisticsPurgeQueuecache is an autogenerated mock type for the StatisticsPurgeQueue type
type StatisticsPurgeQueuecache struct {
	mock.Mock
}

type StatisticsPurgeQueuecache_Expecter struct {
	mock *mock.Mock
}

func (_m *StatisticsPurgeQueuecache) EXPECT() *StatisticsPurgeQueuecache_Expecter {
	return &StatisticsPurgeQueuecache_Expecter{mock: &_m.Mock}
}

// DueStatisticsPurges provides a mock function for the type StatisticsPurgeQueuecache
func (_mock *StatisticsPurgeQueuecache) DueStatisticsPurges(ctx context.Context, now time.Time, limit int) ([]cache.StatisticsPurgeEntry, error) {
	ret := _mock.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for DueStatisticsPurges")
	}

	var r0 []cache.StatisticsPurgeEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]cache.StatisticsPurgeEntry, error)); ok {
		return returnFunc(ctx, now, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []cache.StatisticsPurgeEntry); ok {
		r0 = returnFunc(ctx, now, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cache.StatisticsPurgeEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatisticsPurgeQueuecache_DueStatisticsPurges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DueStatisticsPurges'
type StatisticsPurgeQueuecache_DueStatisticsPurges_Call struct {
	*mock.Call
}

// DueStatisticsPurges is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int
func (_e *StatisticsPurgeQueuecache_Expecter) DueStatisticsPurges(ctx interface{}, now interface{}, limit interface{}) *StatisticsPurgeQueuecache_DueStatisticsPurges_Call {
	return &StatisticsPurgeQueuecache_DueStatisticsPurges_Call{Call: _e.mock.On("DueStatisticsPurges", ctx, now, limit)}
}

func (_c *StatisticsPurgeQueuecache_DueStatisticsPurges_Call) Run(run func(ctx context.Context, now time.Time, limit int)) *StatisticsPurgeQueuecache_DueStatisticsPurges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StatisticsPurgeQueuecache_DueStatisticsPurges_Call) Return(statisticsPurgeEntrys []cache.StatisticsPurgeEntry, err error) *StatisticsPurgeQueuecache_DueStatisticsPurges_Call {
	_c.Call.Return(statisticsPurgeEntrys, err)
	return _c
}

func (_c *StatisticsPurgeQueuecache_DueStatisticsPurges_Call) RunAndReturn(run func(ctx context.Context, now time.Time, limit int) ([]cache.StatisticsPurgeEntry, error)) *StatisticsPurgeQueuecache_DueStatisticsPurges_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueStatisticsPurge provides a mock function for the type StatisticsPurgeQueuecache
func (_mock *StatisticsPurgeQueuecache) EnqueueStatisticsPurge(ctx context.Context, member string, due time.Time) error {
	ret := _mock.Called(ctx, member, due)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueStatisticsPurge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, member, due)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueStatisticsPurge'
type StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call struct {
	*mock.Call
}

// EnqueueStatisticsPurge is a helper method to define mock.On call
//   - ctx context.Context
//   - member string
//   - due time.Time
func (_e *StatisticsPurgeQueuecache_Expecter) EnqueueStatisticsPurge(ctx interface{}, member interface{}, due interface{}) *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call {
	return &StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call{Call: _e.mock.On("EnqueueStatisticsPurge", ctx, member, due)}
}

func (_c *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call) Run(run func(ctx context.Context, member string, due time.Time)) *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call) Return(err error) *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call) RunAndReturn(run func(ctx context.Context, member string, due time.Time) error) *StatisticsPurgeQueuecache_EnqueueStatisticsPurge_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveStatisticsPurge provides a mock function for the type StatisticsPurgeQueuecache
func (_mock *StatisticsPurgeQueuecache) RemoveStatisticsPurge(ctx context.Context, member string) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for RemoveStatisticsPurge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveStatisticsPurge'
type StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call struct {
	*mock.Call
}

// RemoveStatisticsPurge is a helper method to define mock.On call
//   - ctx context.Context
//   - member string
func (_e *StatisticsPurgeQueuecache_Expecter) RemoveStatisticsPurge(ctx interface{}, member interface{}) *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call {
	return &StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call{Call: _e.mock.On("RemoveStatisticsPurge", ctx, member)}
}

func (_c *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call) Run(run func(ctx context.Context, member string)) *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call) Return(err error) *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call) RunAndReturn(run func(ctx context.Context, member string) error) *StatisticsPurgeQueuecache_RemoveStatisticsPurge_Call {
	_c.Call.Return(run)
	return _c
}
