// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewStorereauth creates a new instance of Storereauth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorereauth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storereauth {
	mock := &Storereauth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storereauth is an autogenerated mock type for the Store type
type Storereauth struct {
	mock.Mock
}

type Storereauth_Expecter struct {
	mock *mock.Mock
}

func (_m *Storereauth) EXPECT() *Storereauth_Expecter {
	return &Storereauth_Expecter{mock: &_m.Mock}
}

// GetAccountById provides a mock function for the type Storereauth
func (_mock *Storereauth) GetAccountById(ctx context.Context, accountId string) (*model.Account, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountById")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storereauth_GetAccountById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountById'
type Storereauth_GetAccountById_Call struct {
	*mock.Call
}

// GetAccountById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Storereauth_Expecter) GetAccountById(ctx interface{}, accountId interface{}) *Storereauth_GetAccountById_Call {
	return &Storereauth_GetAccountById_Call{Call: _e.mock.On("GetAccountById", ctx, accountId)}
}

func (_c *Storereauth_GetAccountById_Call) Run(run func(ctx context.Context, accountId string)) *Storereauth_GetAccountById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storereauth_GetAccountById_Call) Return(account *model.Account, err error) *Storereauth_GetAccountById_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Storereauth_GetAccountById_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Account, error)) *Storereauth_GetAccountById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type Storereauth
func (_mock *Storereauth) UpdateAccount(ctx context.Context, account *model.Account) (*model.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) (*model.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storereauth_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type Storereauth_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *Storereauth_Expecter) UpdateAccount(ctx interface{}, account interface{}) *Storereauth_UpdateAccount_Call {
	return &Storereauth_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, account)}
}

func (_c *Storereauth_UpdateAccount_Call) Run(run func(ctx context.Context, account *model.Account)) *Storereauth_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storereauth_UpdateAccount_Call) Return(account1 *model.Account, err error) *Storereauth_UpdateAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *Storereauth_UpdateAccount_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) (*model.Account, error)) *Storereauth_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}
