// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Create(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Create(ctx interface{}, subscription interface{}) *SubscriptionRepository_Create_Call {
	return &SubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *SubscriptionRepository_Create_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Create_Call) Return(err error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindExpiredUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindExpiredUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredUnnotified'
type SubscriptionRepository_FindExpiredUnnotified_Call struct {
	*mock.Call
}

// FindExpiredUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindExpiredUnnotified(ctx interface{}) *SubscriptionRepository_FindExpiredUnnotified_Call {
	return &SubscriptionRepository_FindExpiredUnnotified_Call{Call: _e.mock.On("FindExpiredUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingDeleteUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindPendingDeleteUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingDeleteUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindPendingDeleteUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingDeleteUnnotified'
type SubscriptionRepository_FindPendingDeleteUnnotified_Call struct {
	*mock.Call
}

// FindPendingDeleteUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindPendingDeleteUnnotified(ctx interface{}) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	return &SubscriptionRepository_FindPendingDeleteUnnotified_Call{Call: _e.mock.On("FindPendingDeleteUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) GetSubscriptionByAccountId(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByAccountId")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_GetSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByAccountId'
type SubscriptionRepository_GetSubscriptionByAccountId_Call struct {
	*mock.Call
}

// GetSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) GetSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	return &SubscriptionRepository_GetSubscriptionByAccountId_Call{Call: _e.mock.On("GetSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Return(subscription *model.Subscription, err error) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) MarkNotified(ctx context.Context, subscriptionIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, subscriptionIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_MarkNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotified'
type SubscriptionRepository_MarkNotified_Call struct {
	*mock.Call
}

// MarkNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
func (_e *SubscriptionRepository_Expecter) MarkNotified(ctx interface{}, subscriptionIDs interface{}) *SubscriptionRepository_MarkNotified_Call {
	return &SubscriptionRepository_MarkNotified_Call{Call: _e.mock.On("MarkNotified", ctx, subscriptionIDs)}
}

func (_c *SubscriptionRepository_MarkNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID)) *SubscriptionRepository_MarkNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_MarkNotified_Call) Return(err error) *SubscriptionRepository_MarkNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_MarkNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID) error) *SubscriptionRepository_MarkNotified_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPendingDeleteNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) MarkPendingDeleteNotified(ctx context.Context, subscriptionIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, subscriptionIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkPendingDeleteNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_MarkPendingDeleteNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPendingDeleteNotified'
type SubscriptionRepository_MarkPendingDeleteNotified_Call struct {
	*mock.Call
}

// MarkPendingDeleteNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
func (_e *SubscriptionRepository_Expecter) MarkPendingDeleteNotified(ctx interface{}, subscriptionIDs interface{}) *SubscriptionRepository_MarkPendingDeleteNotified_Call {
	return &SubscriptionRepository_MarkPendingDeleteNotified_Call{Call: _e.mock.On("MarkPendingDeleteNotified", ctx, subscriptionIDs)}
}

func (_c *SubscriptionRepository_MarkPendingDeleteNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID)) *SubscriptionRepository_MarkPendingDeleteNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_MarkPendingDeleteNotified_Call) Return(err error) *SubscriptionRepository_MarkPendingDeleteNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_MarkPendingDeleteNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID) error) *SubscriptionRepository_MarkPendingDeleteNotified_Call {
	_c.Call.Return(run)
	return _c
}

// ResetNotifiedForActive provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) ResetNotifiedForActive(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetNotifiedForActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_ResetNotifiedForActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetNotifiedForActive'
type SubscriptionRepository_ResetNotifiedForActive_Call struct {
	*mock.Call
}

// ResetNotifiedForActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) ResetNotifiedForActive(ctx interface{}) *SubscriptionRepository_ResetNotifiedForActive_Call {
	return &SubscriptionRepository_ResetNotifiedForActive_Call{Call: _e.mock.On("ResetNotifiedForActive", ctx)}
}

func (_c *SubscriptionRepository_ResetNotifiedForActive_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_ResetNotifiedForActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_ResetNotifiedForActive_Call) Return(err error) *SubscriptionRepository_ResetNotifiedForActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_ResetNotifiedForActive_Call) RunAndReturn(run func(ctx context.Context) error) *SubscriptionRepository_ResetNotifiedForActive_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPendingDeleteNotifiedForActive provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) ResetPendingDeleteNotifiedForActive(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetPendingDeleteNotifiedForActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPendingDeleteNotifiedForActive'
type SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call struct {
	*mock.Call
}

// ResetPendingDeleteNotifiedForActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) ResetPendingDeleteNotifiedForActive(ctx interface{}) *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call {
	return &SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call{Call: _e.mock.On("ResetPendingDeleteNotifiedForActive", ctx)}
}

func (_c *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call) Return(err error) *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call) RunAndReturn(run func(ctx context.Context) error) *SubscriptionRepository_ResetPendingDeleteNotifiedForActive_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Upsert(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type SubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Upsert(ctx interface{}, subscription interface{}) *SubscriptionRepository_Upsert_Call {
	return &SubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, subscription)}
}

func (_c *SubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) Return(err error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
