// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionProvidermiddleware creates a new instance of SubscriptionProvidermiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionProvidermiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionProvidermiddleware {
	mock := &SubscriptionProvidermiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionProvidermiddleware is an autogenerated mock type for the SubscriptionProvider type
type SubscriptionProvidermiddleware struct {
	mock.Mock
}

type SubscriptionProvidermiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionProvidermiddleware) EXPECT() *SubscriptionProvidermiddleware_Expecter {
	return &SubscriptionProvidermiddleware_Expecter{mock: &_m.Mock}
}

// GetSubscription provides a mock function for the type SubscriptionProvidermiddleware
func (_mock *SubscriptionProvidermiddleware) GetSubscription(ctx context.Context, accountID string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionProvidermiddleware_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type SubscriptionProvidermiddleware_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *SubscriptionProvidermiddleware_Expecter) GetSubscription(ctx interface{}, accountID interface{}) *SubscriptionProvidermiddleware_GetSubscription_Call {
	return &SubscriptionProvidermiddleware_GetSubscription_Call{Call: _e.mock.On("GetSubscription", ctx, accountID)}
}

func (_c *SubscriptionProvidermiddleware_GetSubscription_Call) Run(run func(ctx context.Context, accountID string)) *SubscriptionProvidermiddleware_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionProvidermiddleware_GetSubscription_Call) Return(subscription *model.Subscription, err error) *SubscriptionProvidermiddleware_GetSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionProvidermiddleware_GetSubscription_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*model.Subscription, error)) *SubscriptionProvidermiddleware_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}
