// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// ClearLegacyType provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) ClearLegacyType(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for ClearLegacyType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_ClearLegacyType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearLegacyType'
type SubscriptionRepository_ClearLegacyType_Call struct {
	*mock.Call
}

// ClearLegacyType is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) ClearLegacyType(ctx interface{}, accountId interface{}) *SubscriptionRepository_ClearLegacyType_Call {
	return &SubscriptionRepository_ClearLegacyType_Call{Call: _e.mock.On("ClearLegacyType", ctx, accountId)}
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) Return(err error) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Create(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Create(ctx interface{}, subscription interface{}) *SubscriptionRepository_Create_Call {
	return &SubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *SubscriptionRepository_Create_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Create_Call) Return(err error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) DeleteSubscriptionByAccountId(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscriptionByAccountId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_DeleteSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscriptionByAccountId'
type SubscriptionRepository_DeleteSubscriptionByAccountId_Call struct {
	*mock.Call
}

// DeleteSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) DeleteSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	return &SubscriptionRepository_DeleteSubscriptionByAccountId_Call{Call: _e.mock.On("DeleteSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) Return(err error) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindExpiredUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindExpiredUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredUnnotified'
type SubscriptionRepository_FindExpiredUnnotified_Call struct {
	*mock.Call
}

// FindExpiredUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindExpiredUnnotified(ctx interface{}) *SubscriptionRepository_FindExpiredUnnotified_Call {
	return &SubscriptionRepository_FindExpiredUnnotified_Call{Call: _e.mock.On("FindExpiredUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingDeleteUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindPendingDeleteUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingDeleteUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindPendingDeleteUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingDeleteUnnotified'
type SubscriptionRepository_FindPendingDeleteUnnotified_Call struct {
	*mock.Call
}

// FindPendingDeleteUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindPendingDeleteUnnotified(ctx interface{}) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	return &SubscriptionRepository_FindPendingDeleteUnnotified_Call{Call: _e.mock.On("FindPendingDeleteUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindPendingDeleteUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindPendingDeleteUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithLANotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindWithLANotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindWithLANotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindWithLANotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithLANotified'
type SubscriptionRepository_FindWithLANotified_Call struct {
	*mock.Call
}

// FindWithLANotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindWithLANotified(ctx interface{}) *SubscriptionRepository_FindWithLANotified_Call {
	return &SubscriptionRepository_FindWithLANotified_Call{Call: _e.mock.On("FindWithLANotified", ctx)}
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithPendingDeleteNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindWithPendingDeleteNotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindWithPendingDeleteNotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindWithPendingDeleteNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithPendingDeleteNotified'
type SubscriptionRepository_FindWithPendingDeleteNotified_Call struct {
	*mock.Call
}

// FindWithPendingDeleteNotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindWithPendingDeleteNotified(ctx interface{}) *SubscriptionRepository_FindWithPendingDeleteNotified_Call {
	return &SubscriptionRepository_FindWithPendingDeleteNotified_Call{Call: _e.mock.On("FindWithPendingDeleteNotified", ctx)}
}

func (_c *SubscriptionRepository_FindWithPendingDeleteNotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindWithPendingDeleteNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindWithPendingDeleteNotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindWithPendingDeleteNotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindWithPendingDeleteNotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindWithPendingDeleteNotified_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) GetSubscriptionByAccountId(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByAccountId")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_GetSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByAccountId'
type SubscriptionRepository_GetSubscriptionByAccountId_Call struct {
	*mock.Call
}

// GetSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) GetSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	return &SubscriptionRepository_GetSubscriptionByAccountId_Call{Call: _e.mock.On("GetSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Return(subscription *model.Subscription, err error) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// SetNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) SetNotified(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error {
	ret := _mock.Called(ctx, subscriptionIDs, value)

	if len(ret) == 0 {
		panic("no return value specified for SetNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_SetNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotified'
type SubscriptionRepository_SetNotified_Call struct {
	*mock.Call
}

// SetNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
//   - value bool
func (_e *SubscriptionRepository_Expecter) SetNotified(ctx interface{}, subscriptionIDs interface{}, value interface{}) *SubscriptionRepository_SetNotified_Call {
	return &SubscriptionRepository_SetNotified_Call{Call: _e.mock.On("SetNotified", ctx, subscriptionIDs, value)}
}

func (_c *SubscriptionRepository_SetNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool)) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_SetNotified_Call) Return(err error) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_SetNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Return(run)
	return _c
}

// SetPendingDeleteNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) SetPendingDeleteNotified(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error {
	ret := _mock.Called(ctx, subscriptionIDs, value)

	if len(ret) == 0 {
		panic("no return value specified for SetPendingDeleteNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_SetPendingDeleteNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPendingDeleteNotified'
type SubscriptionRepository_SetPendingDeleteNotified_Call struct {
	*mock.Call
}

// SetPendingDeleteNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
//   - value bool
func (_e *SubscriptionRepository_Expecter) SetPendingDeleteNotified(ctx interface{}, subscriptionIDs interface{}, value interface{}) *SubscriptionRepository_SetPendingDeleteNotified_Call {
	return &SubscriptionRepository_SetPendingDeleteNotified_Call{Call: _e.mock.On("SetPendingDeleteNotified", ctx, subscriptionIDs, value)}
}

func (_c *SubscriptionRepository_SetPendingDeleteNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool)) *SubscriptionRepository_SetPendingDeleteNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_SetPendingDeleteNotified_Call) Return(err error) *SubscriptionRepository_SetPendingDeleteNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_SetPendingDeleteNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error) *SubscriptionRepository_SetPendingDeleteNotified_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Upsert(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type SubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Upsert(ctx interface{}, subscription interface{}) *SubscriptionRepository_Upsert_Call {
	return &SubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, subscription)}
}

func (_c *SubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) Return(err error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
