// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionServicer creates a new instance of SubscriptionServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionServicer {
	mock := &SubscriptionServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionServicer is an autogenerated mock type for the SubscriptionServicer type
type SubscriptionServicer struct {
	mock.Mock
}

type SubscriptionServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionServicer) EXPECT() *SubscriptionServicer_Expecter {
	return &SubscriptionServicer_Expecter{mock: &_m.Mock}
}

// AddPASession provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) AddPASession(ctx context.Context, session *model.PASession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for AddPASession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PASession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionServicer_AddPASession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPASession'
type SubscriptionServicer_AddPASession_Call struct {
	*mock.Call
}

// AddPASession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.PASession
func (_e *SubscriptionServicer_Expecter) AddPASession(ctx interface{}, session interface{}) *SubscriptionServicer_AddPASession_Call {
	return &SubscriptionServicer_AddPASession_Call{Call: _e.mock.On("AddPASession", ctx, session)}
}

func (_c *SubscriptionServicer_AddPASession_Call) Run(run func(ctx context.Context, session *model.PASession)) *SubscriptionServicer_AddPASession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PASession
		if args[1] != nil {
			arg1 = args[1].(*model.PASession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_AddPASession_Call) Return(err error) *SubscriptionServicer_AddPASession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionServicer_AddPASession_Call) RunAndReturn(run func(ctx context.Context, session *model.PASession) error) *SubscriptionServicer_AddPASession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscriptionFromPreauth provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) CreateSubscriptionFromPreauth(ctx context.Context, accountId string, preauth *model.Preauth) error {
	ret := _mock.Called(ctx, accountId, preauth)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscriptionFromPreauth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Preauth) error); ok {
		r0 = returnFunc(ctx, accountId, preauth)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionServicer_CreateSubscriptionFromPreauth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscriptionFromPreauth'
type SubscriptionServicer_CreateSubscriptionFromPreauth_Call struct {
	*mock.Call
}

// CreateSubscriptionFromPreauth is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - preauth *model.Preauth
func (_e *SubscriptionServicer_Expecter) CreateSubscriptionFromPreauth(ctx interface{}, accountId interface{}, preauth interface{}) *SubscriptionServicer_CreateSubscriptionFromPreauth_Call {
	return &SubscriptionServicer_CreateSubscriptionFromPreauth_Call{Call: _e.mock.On("CreateSubscriptionFromPreauth", ctx, accountId, preauth)}
}

func (_c *SubscriptionServicer_CreateSubscriptionFromPreauth_Call) Run(run func(ctx context.Context, accountId string, preauth *model.Preauth)) *SubscriptionServicer_CreateSubscriptionFromPreauth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Preauth
		if args[2] != nil {
			arg2 = args[2].(*model.Preauth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_CreateSubscriptionFromPreauth_Call) Return(err error) *SubscriptionServicer_CreateSubscriptionFromPreauth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionServicer_CreateSubscriptionFromPreauth_Call) RunAndReturn(run func(ctx context.Context, accountId string, preauth *model.Preauth) error) *SubscriptionServicer_CreateSubscriptionFromPreauth_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) GetSubscription(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type SubscriptionServicer_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionServicer_Expecter) GetSubscription(ctx interface{}, accountId interface{}) *SubscriptionServicer_GetSubscription_Call {
	return &SubscriptionServicer_GetSubscription_Call{Call: _e.mock.On("GetSubscription", ctx, accountId)}
}

func (_c *SubscriptionServicer_GetSubscription_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_GetSubscription_Call) Return(subscription *model.Subscription, err error) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionServicer_GetSubscription_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionById provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) GetSubscriptionById(ctx context.Context, subscriptionId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionById")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, subscriptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, subscriptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_GetSubscriptionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionById'
type SubscriptionServicer_GetSubscriptionById_Call struct {
	*mock.Call
}

// GetSubscriptionById is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
func (_e *SubscriptionServicer_Expecter) GetSubscriptionById(ctx interface{}, subscriptionId interface{}) *SubscriptionServicer_GetSubscriptionById_Call {
	return &SubscriptionServicer_GetSubscriptionById_Call{Call: _e.mock.On("GetSubscriptionById", ctx, subscriptionId)}
}

func (_c *SubscriptionServicer_GetSubscriptionById_Call) Run(run func(ctx context.Context, subscriptionId string)) *SubscriptionServicer_GetSubscriptionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_GetSubscriptionById_Call) Return(subscription *model.Subscription, err error) *SubscriptionServicer_GetSubscriptionById_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionServicer_GetSubscriptionById_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string) (*model.Subscription, error)) *SubscriptionServicer_GetSubscriptionById_Call {
	_c.Call.Return(run)
	return _c
}

// RotatePASessionID provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) RotatePASessionID(ctx context.Context, oldID string) (string, error) {
	ret := _mock.Called(ctx, oldID)

	if len(ret) == 0 {
		panic("no return value specified for RotatePASessionID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, oldID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, oldID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, oldID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_RotatePASessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotatePASessionID'
type SubscriptionServicer_RotatePASessionID_Call struct {
	*mock.Call
}

// RotatePASessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - oldID string
func (_e *SubscriptionServicer_Expecter) RotatePASessionID(ctx interface{}, oldID interface{}) *SubscriptionServicer_RotatePASessionID_Call {
	return &SubscriptionServicer_RotatePASessionID_Call{Call: _e.mock.On("RotatePASessionID", ctx, oldID)}
}

func (_c *SubscriptionServicer_RotatePASessionID_Call) Run(run func(ctx context.Context, oldID string)) *SubscriptionServicer_RotatePASessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_RotatePASessionID_Call) Return(s string, err error) *SubscriptionServicer_RotatePASessionID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SubscriptionServicer_RotatePASessionID_Call) RunAndReturn(run func(ctx context.Context, oldID string) (string, error)) *SubscriptionServicer_RotatePASessionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) UpdateSubscription(ctx context.Context, accountId string, updates []model.SubscriptionUpdate) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.SubscriptionUpdate) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.SubscriptionUpdate) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []model.SubscriptionUpdate) error); ok {
		r1 = returnFunc(ctx, accountId, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_UpdateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscription'
type SubscriptionServicer_UpdateSubscription_Call struct {
	*mock.Call
}

// UpdateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - updates []model.SubscriptionUpdate
func (_e *SubscriptionServicer_Expecter) UpdateSubscription(ctx interface{}, accountId interface{}, updates interface{}) *SubscriptionServicer_UpdateSubscription_Call {
	return &SubscriptionServicer_UpdateSubscription_Call{Call: _e.mock.On("UpdateSubscription", ctx, accountId, updates)}
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) Run(run func(ctx context.Context, accountId string, updates []model.SubscriptionUpdate)) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.SubscriptionUpdate
		if args[2] != nil {
			arg2 = args[2].([]model.SubscriptionUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) Return(subscription *model.Subscription, err error) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) RunAndReturn(run func(ctx context.Context, accountId string, updates []model.SubscriptionUpdate) (*model.Subscription, error)) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscriptionFromPASession provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) UpdateSubscriptionFromPASession(ctx context.Context, sub *model.Subscription, subID string, sessionID string) error {
	ret := _mock.Called(ctx, sub, subID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscriptionFromPASession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Subscription, string, string) error); ok {
		r0 = returnFunc(ctx, sub, subID, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionServicer_UpdateSubscriptionFromPASession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscriptionFromPASession'
type SubscriptionServicer_UpdateSubscriptionFromPASession_Call struct {
	*mock.Call
}

// UpdateSubscriptionFromPASession is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *model.Subscription
//   - subID string
//   - sessionID string
func (_e *SubscriptionServicer_Expecter) UpdateSubscriptionFromPASession(ctx interface{}, sub interface{}, subID interface{}, sessionID interface{}) *SubscriptionServicer_UpdateSubscriptionFromPASession_Call {
	return &SubscriptionServicer_UpdateSubscriptionFromPASession_Call{Call: _e.mock.On("UpdateSubscriptionFromPASession", ctx, sub, subID, sessionID)}
}

func (_c *SubscriptionServicer_UpdateSubscriptionFromPASession_Call) Run(run func(ctx context.Context, sub *model.Subscription, subID string, sessionID string)) *SubscriptionServicer_UpdateSubscriptionFromPASession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Subscription
		if args[1] != nil {
			arg1 = args[1].(*model.Subscription)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscriptionFromPASession_Call) Return(err error) *SubscriptionServicer_UpdateSubscriptionFromPASession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscriptionFromPASession_Call) RunAndReturn(run func(ctx context.Context, sub *model.Subscription, subID string, sessionID string) error) *SubscriptionServicer_UpdateSubscriptionFromPASession_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAndGetPreauth provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) ValidateAndGetPreauth(ctx context.Context, sessionID string) (*model.Preauth, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndGetPreauth")
	}

	var r0 *model.Preauth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Preauth, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Preauth); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Preauth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_ValidateAndGetPreauth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAndGetPreauth'
type SubscriptionServicer_ValidateAndGetPreauth_Call struct {
	*mock.Call
}

// ValidateAndGetPreauth is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SubscriptionServicer_Expecter) ValidateAndGetPreauth(ctx interface{}, sessionID interface{}) *SubscriptionServicer_ValidateAndGetPreauth_Call {
	return &SubscriptionServicer_ValidateAndGetPreauth_Call{Call: _e.mock.On("ValidateAndGetPreauth", ctx, sessionID)}
}

func (_c *SubscriptionServicer_ValidateAndGetPreauth_Call) Run(run func(ctx context.Context, sessionID string)) *SubscriptionServicer_ValidateAndGetPreauth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_ValidateAndGetPreauth_Call) Return(preauth *model.Preauth, err error) *SubscriptionServicer_ValidateAndGetPreauth_Call {
	_c.Call.Return(preauth, err)
	return _c
}

func (_c *SubscriptionServicer_ValidateAndGetPreauth_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*model.Preauth, error)) *SubscriptionServicer_ValidateAndGetPreauth_Call {
	_c.Call.Return(run)
	return _c
}
