// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// ClearLegacyType provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) ClearLegacyType(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for ClearLegacyType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_ClearLegacyType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearLegacyType'
type SubscriptionRepository_ClearLegacyType_Call struct {
	*mock.Call
}

// ClearLegacyType is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) ClearLegacyType(ctx interface{}, accountId interface{}) *SubscriptionRepository_ClearLegacyType_Call {
	return &SubscriptionRepository_ClearLegacyType_Call{Call: _e.mock.On("ClearLegacyType", ctx, accountId)}
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) Return(err error) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_ClearLegacyType_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *SubscriptionRepository_ClearLegacyType_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Create(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Create(ctx interface{}, subscription interface{}) *SubscriptionRepository_Create_Call {
	return &SubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *SubscriptionRepository_Create_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Create_Call) Return(err error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) DeleteSubscriptionByAccountId(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscriptionByAccountId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_DeleteSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscriptionByAccountId'
type SubscriptionRepository_DeleteSubscriptionByAccountId_Call struct {
	*mock.Call
}

// DeleteSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) DeleteSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	return &SubscriptionRepository_DeleteSubscriptionByAccountId_Call{Call: _e.mock.On("DeleteSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) Return(err error) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_DeleteSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *SubscriptionRepository_DeleteSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByTokenHash provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string, excludeAccountID primitive.ObjectID) ([]model.Subscription, error) {
	ret := _mock.Called(ctx, tokenHash, excludeAccountID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByTokenHash")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID) ([]model.Subscription, error)); ok {
		return returnFunc(ctx, tokenHash, excludeAccountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, primitive.ObjectID) []model.Subscription); ok {
		r0 = returnFunc(ctx, tokenHash, excludeAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, tokenHash, excludeAccountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindActiveByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByTokenHash'
type SubscriptionRepository_FindActiveByTokenHash_Call struct {
	*mock.Call
}

// FindActiveByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - excludeAccountID primitive.ObjectID
func (_e *SubscriptionRepository_Expecter) FindActiveByTokenHash(ctx interface{}, tokenHash interface{}, excludeAccountID interface{}) *SubscriptionRepository_FindActiveByTokenHash_Call {
	return &SubscriptionRepository_FindActiveByTokenHash_Call{Call: _e.mock.On("FindActiveByTokenHash", ctx, tokenHash, excludeAccountID)}
}

func (_c *SubscriptionRepository_FindActiveByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string, excludeAccountID primitive.ObjectID)) *SubscriptionRepository_FindActiveByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindActiveByTokenHash_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindActiveByTokenHash_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindActiveByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, excludeAccountID primitive.ObjectID) ([]model.Subscription, error)) *SubscriptionRepository_FindActiveByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindDuplicateTokenHashGroups provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindDuplicateTokenHashGroups(ctx context.Context) ([]model.DuplicateTokenHashGroup, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindDuplicateTokenHashGroups")
	}

	var r0 []model.DuplicateTokenHashGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.DuplicateTokenHashGroup, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.DuplicateTokenHashGroup); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DuplicateTokenHashGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindDuplicateTokenHashGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDuplicateTokenHashGroups'
type SubscriptionRepository_FindDuplicateTokenHashGroups_Call struct {
	*mock.Call
}

// FindDuplicateTokenHashGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindDuplicateTokenHashGroups(ctx interface{}) *SubscriptionRepository_FindDuplicateTokenHashGroups_Call {
	return &SubscriptionRepository_FindDuplicateTokenHashGroups_Call{Call: _e.mock.On("FindDuplicateTokenHashGroups", ctx)}
}

func (_c *SubscriptionRepository_FindDuplicateTokenHashGroups_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindDuplicateTokenHashGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindDuplicateTokenHashGroups_Call) Return(duplicateTokenHashGroups []model.DuplicateTokenHashGroup, err error) *SubscriptionRepository_FindDuplicateTokenHashGroups_Call {
	_c.Call.Return(duplicateTokenHashGroups, err)
	return _c
}

func (_c *SubscriptionRepository_FindDuplicateTokenHashGroups_Call) RunAndReturn(run func(ctx context.Context) ([]model.DuplicateTokenHashGroup, error)) *SubscriptionRepository_FindDuplicateTokenHashGroups_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindExpiredUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindExpiredUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredUnnotified'
type SubscriptionRepository_FindExpiredUnnotified_Call struct {
	*mock.Call
}

// FindExpiredUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindExpiredUnnotified(ctx interface{}) *SubscriptionRepository_FindExpiredUnnotified_Call {
	return &SubscriptionRepository_FindExpiredUnnotified_Call{Call: _e.mock.On("FindExpiredUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindExpiredUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindExpiredUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindInactiveUnnotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindInactiveUnnotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindInactiveUnnotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindInactiveUnnotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindInactiveUnnotified'
type SubscriptionRepository_FindInactiveUnnotified_Call struct {
	*mock.Call
}

// FindInactiveUnnotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindInactiveUnnotified(ctx interface{}) *SubscriptionRepository_FindInactiveUnnotified_Call {
	return &SubscriptionRepository_FindInactiveUnnotified_Call{Call: _e.mock.On("FindInactiveUnnotified", ctx)}
}

func (_c *SubscriptionRepository_FindInactiveUnnotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindInactiveUnnotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindInactiveUnnotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindInactiveUnnotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindInactiveUnnotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindInactiveUnnotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindScheduledForDeletion provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindScheduledForDeletion(ctx context.Context, before time.Time) ([]model.Subscription, error) {
	ret := _mock.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindScheduledForDeletion")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.Subscription, error)); ok {
		return returnFunc(ctx, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []model.Subscription); ok {
		r0 = returnFunc(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindScheduledForDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindScheduledForDeletion'
type SubscriptionRepository_FindScheduledForDeletion_Call struct {
	*mock.Call
}

// FindScheduledForDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *SubscriptionRepository_Expecter) FindScheduledForDeletion(ctx interface{}, before interface{}) *SubscriptionRepository_FindScheduledForDeletion_Call {
	return &SubscriptionRepository_FindScheduledForDeletion_Call{Call: _e.mock.On("FindScheduledForDeletion", ctx, before)}
}

func (_c *SubscriptionRepository_FindScheduledForDeletion_Call) Run(run func(ctx context.Context, before time.Time)) *SubscriptionRepository_FindScheduledForDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindScheduledForDeletion_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindScheduledForDeletion_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindScheduledForDeletion_Call) RunAndReturn(run func(ctx context.Context, before time.Time) ([]model.Subscription, error)) *SubscriptionRepository_FindScheduledForDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithInactiveNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindWithInactiveNotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindWithInactiveNotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindWithInactiveNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithInactiveNotified'
type SubscriptionRepository_FindWithInactiveNotified_Call struct {
	*mock.Call
}

// FindWithInactiveNotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindWithInactiveNotified(ctx interface{}) *SubscriptionRepository_FindWithInactiveNotified_Call {
	return &SubscriptionRepository_FindWithInactiveNotified_Call{Call: _e.mock.On("FindWithInactiveNotified", ctx)}
}

func (_c *SubscriptionRepository_FindWithInactiveNotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindWithInactiveNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindWithInactiveNotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindWithInactiveNotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindWithInactiveNotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindWithInactiveNotified_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithLANotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) FindWithLANotified(ctx context.Context) ([]model.Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindWithLANotified")
	}

	var r0 []model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_FindWithLANotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithLANotified'
type SubscriptionRepository_FindWithLANotified_Call struct {
	*mock.Call
}

// FindWithLANotified is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SubscriptionRepository_Expecter) FindWithLANotified(ctx interface{}) *SubscriptionRepository_FindWithLANotified_Call {
	return &SubscriptionRepository_FindWithLANotified_Call{Call: _e.mock.On("FindWithLANotified", ctx)}
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) Run(run func(ctx context.Context)) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) Return(subscriptions []model.Subscription, err error) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *SubscriptionRepository_FindWithLANotified_Call) RunAndReturn(run func(ctx context.Context) ([]model.Subscription, error)) *SubscriptionRepository_FindWithLANotified_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) GetSubscriptionByAccountId(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByAccountId")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_GetSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByAccountId'
type SubscriptionRepository_GetSubscriptionByAccountId_Call struct {
	*mock.Call
}

// GetSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) GetSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	return &SubscriptionRepository_GetSubscriptionByAccountId_Call{Call: _e.mock.On("GetSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Return(subscription *model.Subscription, err error) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSubscriptionRetired provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) MarkSubscriptionRetired(ctx context.Context, subscriptionID uuid.UUID, when time.Time) error {
	ret := _mock.Called(ctx, subscriptionID, when)

	if len(ret) == 0 {
		panic("no return value specified for MarkSubscriptionRetired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, subscriptionID, when)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_MarkSubscriptionRetired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSubscriptionRetired'
type SubscriptionRepository_MarkSubscriptionRetired_Call struct {
	*mock.Call
}

// MarkSubscriptionRetired is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID uuid.UUID
//   - when time.Time
func (_e *SubscriptionRepository_Expecter) MarkSubscriptionRetired(ctx interface{}, subscriptionID interface{}, when interface{}) *SubscriptionRepository_MarkSubscriptionRetired_Call {
	return &SubscriptionRepository_MarkSubscriptionRetired_Call{Call: _e.mock.On("MarkSubscriptionRetired", ctx, subscriptionID, when)}
}

func (_c *SubscriptionRepository_MarkSubscriptionRetired_Call) Run(run func(ctx context.Context, subscriptionID uuid.UUID, when time.Time)) *SubscriptionRepository_MarkSubscriptionRetired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_MarkSubscriptionRetired_Call) Return(err error) *SubscriptionRepository_MarkSubscriptionRetired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_MarkSubscriptionRetired_Call) RunAndReturn(run func(ctx context.Context, subscriptionID uuid.UUID, when time.Time) error) *SubscriptionRepository_MarkSubscriptionRetired_Call {
	_c.Call.Return(run)
	return _c
}

// SetInactiveNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) SetInactiveNotified(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error {
	ret := _mock.Called(ctx, subscriptionIDs, value)

	if len(ret) == 0 {
		panic("no return value specified for SetInactiveNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_SetInactiveNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInactiveNotified'
type SubscriptionRepository_SetInactiveNotified_Call struct {
	*mock.Call
}

// SetInactiveNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
//   - value bool
func (_e *SubscriptionRepository_Expecter) SetInactiveNotified(ctx interface{}, subscriptionIDs interface{}, value interface{}) *SubscriptionRepository_SetInactiveNotified_Call {
	return &SubscriptionRepository_SetInactiveNotified_Call{Call: _e.mock.On("SetInactiveNotified", ctx, subscriptionIDs, value)}
}

func (_c *SubscriptionRepository_SetInactiveNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool)) *SubscriptionRepository_SetInactiveNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_SetInactiveNotified_Call) Return(err error) *SubscriptionRepository_SetInactiveNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_SetInactiveNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error) *SubscriptionRepository_SetInactiveNotified_Call {
	_c.Call.Return(run)
	return _c
}

// SetNotified provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) SetNotified(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error {
	ret := _mock.Called(ctx, subscriptionIDs, value)

	if len(ret) == 0 {
		panic("no return value specified for SetNotified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, subscriptionIDs, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_SetNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotified'
type SubscriptionRepository_SetNotified_Call struct {
	*mock.Call
}

// SetNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionIDs []uuid.UUID
//   - value bool
func (_e *SubscriptionRepository_Expecter) SetNotified(ctx interface{}, subscriptionIDs interface{}, value interface{}) *SubscriptionRepository_SetNotified_Call {
	return &SubscriptionRepository_SetNotified_Call{Call: _e.mock.On("SetNotified", ctx, subscriptionIDs, value)}
}

func (_c *SubscriptionRepository_SetNotified_Call) Run(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool)) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_SetNotified_Call) Return(err error) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_SetNotified_Call) RunAndReturn(run func(ctx context.Context, subscriptionIDs []uuid.UUID, value bool) error) *SubscriptionRepository_SetNotified_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Upsert(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type SubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Upsert(ctx interface{}, subscription interface{}) *SubscriptionRepository_Upsert_Call {
	return &SubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, subscription)}
}

func (_c *SubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) Return(err error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
