// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/service/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewUnconsentedQueryLogsPurgercron creates a new instance of UnconsentedQueryLogsPurgercron. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnconsentedQueryLogsPurgercron(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnconsentedQueryLogsPurgercron {
	mock := &UnconsentedQueryLogsPurgercron{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnconsentedQueryLogsPurgercron is an autogenerated mock type for the UnconsentedQueryLogsPurger type
type UnconsentedQueryLogsPurgercron struct {
	mock.Mock
}

type UnconsentedQueryLogsPurgercron_Expecter struct {
	mock *mock.Mock
}

func (_m *UnconsentedQueryLogsPurgercron) EXPECT() *UnconsentedQueryLogsPurgercron_Expecter {
	return &UnconsentedQueryLogsPurgercron_Expecter{mock: &_m.Mock}
}

// PurgeUnconsentedQueryLogs provides a mock function for the type UnconsentedQueryLogsPurgercron
func (_mock *UnconsentedQueryLogsPurgercron) PurgeUnconsentedQueryLogs(ctx context.Context) (profile.UnconsentedQueryLogsPurgeResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PurgeUnconsentedQueryLogs")
	}

	var r0 profile.UnconsentedQueryLogsPurgeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (profile.UnconsentedQueryLogsPurgeResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) profile.UnconsentedQueryLogsPurgeResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(profile.UnconsentedQueryLogsPurgeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeUnconsentedQueryLogs'
type UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call struct {
	*mock.Call
}

// PurgeUnconsentedQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnconsentedQueryLogsPurgercron_Expecter) PurgeUnconsentedQueryLogs(ctx interface{}) *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call {
	return &UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call{Call: _e.mock.On("PurgeUnconsentedQueryLogs", ctx)}
}

func (_c *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call) Run(run func(ctx context.Context)) *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call) Return(unconsentedQueryLogsPurgeResult profile.UnconsentedQueryLogsPurgeResult, err error) *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call {
	_c.Call.Return(unconsentedQueryLogsPurgeResult, err)
	return _c
}

func (_c *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call) RunAndReturn(run func(ctx context.Context) (profile.UnconsentedQueryLogsPurgeResult, error)) *UnconsentedQueryLogsPurgercron_PurgeUnconsentedQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}
