// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/service/statistics"
	mock "github.com/stretchr/testify/mock"
)

// NewUnconsentedStatisticsPurgercron creates a new instance of UnconsentedStatisticsPurgercron. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnconsentedStatisticsPurgercron(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnconsentedStatisticsPurgercron {
	mock := &UnconsentedStatisticsPurgercron{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnconsentedStatisticsPurgercron is an autogenerated mock type for the UnconsentedStatisticsPurger type
type UnconsentedStatisticsPurgercron struct {
	mock.Mock
}

type UnconsentedStatisticsPurgercron_Expecter struct {
	mock *mock.Mock
}

func (_m *UnconsentedStatisticsPurgercron) EXPECT() *UnconsentedStatisticsPurgercron_Expecter {
	return &UnconsentedStatisticsPurgercron_Expecter{mock: &_m.Mock}
}

// PurgeUnconsentedStatistics provides a mock function for the type UnconsentedStatisticsPurgercron
func (_mock *UnconsentedStatisticsPurgercron) PurgeUnconsentedStatistics(ctx context.Context) (statistics.UnconsentedPurgeResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PurgeUnconsentedStatistics")
	}

	var r0 statistics.UnconsentedPurgeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (statistics.UnconsentedPurgeResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) statistics.UnconsentedPurgeResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(statistics.UnconsentedPurgeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeUnconsentedStatistics'
type UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call struct {
	*mock.Call
}

// PurgeUnconsentedStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnconsentedStatisticsPurgercron_Expecter) PurgeUnconsentedStatistics(ctx interface{}) *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call {
	return &UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call{Call: _e.mock.On("PurgeUnconsentedStatistics", ctx)}
}

func (_c *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call) Run(run func(ctx context.Context)) *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call) Return(unconsentedPurgeResult statistics.UnconsentedPurgeResult, err error) *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call {
	_c.Call.Return(unconsentedPurgeResult, err)
	return _c
}

func (_c *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call) RunAndReturn(run func(ctx context.Context) (statistics.UnconsentedPurgeResult, error)) *UnconsentedStatisticsPurgercron_PurgeUnconsentedStatistics_Call {
	_c.Call.Return(run)
	return _c
}
